/**
 * Country and city to emoji flag mapping
 * Used for dynamic suggestions in chat
 */

export const countryEmojis: Record<string, string> = {
  // Countries - French
  "espagne": "🇪🇸",
  "portugal": "🇵🇹",
  "italie": "🇮🇹",
  "france": "🇫🇷",
  "grèce": "🇬🇷",
  "grece": "🇬🇷",
  "allemagne": "🇩🇪",
  "royaume-uni": "🇬🇧",
  "angleterre": "🇬🇧",
  "états-unis": "🇺🇸",
  "etats-unis": "🇺🇸",
  "usa": "🇺🇸",
  "japon": "🇯🇵",
  "chine": "🇨🇳",
  "thaïlande": "🇹🇭",
  "thailande": "🇹🇭",
  "vietnam": "🇻🇳",
  "indonésie": "🇮🇩",
  "indonesie": "🇮🇩",
  "maroc": "🇲🇦",
  "tunisie": "🇹🇳",
  "égypte": "🇪🇬",
  "egypte": "🇪🇬",
  "turquie": "🇹🇷",
  "croatie": "🇭🇷",
  "mexique": "🇲🇽",
  "brésil": "🇧🇷",
  "bresil": "🇧🇷",
  "argentine": "🇦🇷",
  "australie": "🇦🇺",
  "nouvelle-zélande": "🇳🇿",
  "canada": "🇨🇦",
  "suisse": "🇨🇭",
  "belgique": "🇧🇪",
  "pays-bas": "🇳🇱",
  "hollande": "🇳🇱",
  "autriche": "🇦🇹",
  "pologne": "🇵🇱",
  "république tchèque": "🇨🇿",
  "hongrie": "🇭🇺",
  "suède": "🇸🇪",
  "norvège": "🇳🇴",
  "danemark": "🇩🇰",
  "finlande": "🇫🇮",
  "irlande": "🇮🇪",
  "écosse": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "qatar": "🇶🇦",
  "émirats arabes unis": "🇦🇪",
  "dubai": "🇦🇪",
  "singapour": "🇸🇬",
  "corée du sud": "🇰🇷",
  "inde": "🇮🇳",
  "sri lanka": "🇱🇰",
  "maldives": "🇲🇻",
  "maurice": "🇲🇺",
  "réunion": "🇷🇪",
  "martinique": "🇲🇶",
  "guadeloupe": "🇬🇵",
  "cuba": "🇨🇺",
  "république dominicaine": "🇩🇴",
  "colombie": "🇨🇴",
  "pérou": "🇵🇪",
  "chili": "🇨🇱",
  
  // Major cities - Spanish
  "barcelone": "🇪🇸",
  "barcelona": "🇪🇸",
  "madrid": "🇪🇸",
  "séville": "🇪🇸",
  "seville": "🇪🇸",
  "valence": "🇪🇸",
  "valencia": "🇪🇸",
  "malaga": "🇪🇸",
  "ibiza": "🇪🇸",
  "majorque": "🇪🇸",
  "palma": "🇪🇸",
  
  // Portuguese
  "lisbonne": "🇵🇹",
  "lisbon": "🇵🇹",
  "lisboa": "🇵🇹",
  "porto": "🇵🇹",
  "faro": "🇵🇹",
  
  // Italian
  "rome": "🇮🇹",
  "roma": "🇮🇹",
  "milan": "🇮🇹",
  "milano": "🇮🇹",
  "venise": "🇮🇹",
  "venice": "🇮🇹",
  "venezia": "🇮🇹",
  "florence": "🇮🇹",
  "firenze": "🇮🇹",
  "naples": "🇮🇹",
  "napoli": "🇮🇹",
  "pise": "🇮🇹",
  "pisa": "🇮🇹",
  "sicile": "🇮🇹",
  "sardaigne": "🇮🇹",
  
  // French
  "paris": "🇫🇷",
  "nice": "🇫🇷",
  "lyon": "🇫🇷",
  "marseille": "🇫🇷",
  "bordeaux": "🇫🇷",
  "toulouse": "🇫🇷",
  "montpellier": "🇫🇷",
  "strasbourg": "🇫🇷",
  "nantes": "🇫🇷",
  "lille": "🇫🇷",
  "corse": "🇫🇷",
  
  // Greek
  "athènes": "🇬🇷",
  "athenes": "🇬🇷",
  "athens": "🇬🇷",
  "santorini": "🇬🇷",
  "santorin": "🇬🇷",
  "mykonos": "🇬🇷",
  "crète": "🇬🇷",
  "crete": "🇬🇷",
  "rhodes": "🇬🇷",
  "corfou": "🇬🇷",
  
  // German
  "berlin": "🇩🇪",
  "munich": "🇩🇪",
  "münchen": "🇩🇪",
  "francfort": "🇩🇪",
  "frankfurt": "🇩🇪",
  "hambourg": "🇩🇪",
  "hamburg": "🇩🇪",
  "cologne": "🇩🇪",
  "köln": "🇩🇪",
  
  // UK
  "londres": "🇬🇧",
  "london": "🇬🇧",
  "manchester": "🇬🇧",
  "birmingham": "🇬🇧",
  "édimbourg": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "edinburgh": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "glasgow": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  
  // USA
  "new york": "🇺🇸",
  "los angeles": "🇺🇸",
  "miami": "🇺🇸",
  "san francisco": "🇺🇸",
  "las vegas": "🇺🇸",
  "chicago": "🇺🇸",
  "boston": "🇺🇸",
  "washington": "🇺🇸",
  "seattle": "🇺🇸",
  "hawaii": "🇺🇸",
  "hawaï": "🇺🇸",
  
  // Japan
  "tokyo": "🇯🇵",
  "kyoto": "🇯🇵",
  "osaka": "🇯🇵",
  "hiroshima": "🇯🇵",
  
  // Thailand
  "bangkok": "🇹🇭",
  "phuket": "🇹🇭",
  "chiang mai": "🇹🇭",
  "koh samui": "🇹🇭",
  
  // Other Asian
  "bali": "🇮🇩",
  "singapour city": "🇸🇬",
  "hong kong": "🇭🇰",
  "hô chi minh": "🇻🇳",
  "ho chi minh": "🇻🇳",
  "hanoi": "🇻🇳",
  "hanoï": "🇻🇳",
  "séoul": "🇰🇷",
  "seoul": "🇰🇷",
  "pékin": "🇨🇳",
  "pekin": "🇨🇳",
  "beijing": "🇨🇳",
  "shanghai": "🇨🇳",
  
  // Middle East
  "doha": "🇶🇦",
  "abu dhabi": "🇦🇪",
  "tel aviv": "🇮🇱",
  "jérusalem": "🇮🇱",
  "jerusalem": "🇮🇱",
  "amman": "🇯🇴",
  "beyrouth": "🇱🇧",
  "beirut": "🇱🇧",
  "istanbul": "🇹🇷",
  
  // African
  "marrakech": "🇲🇦",
  "casablanca": "🇲🇦",
  "agadir": "🇲🇦",
  "fès": "🇲🇦",
  "fes": "🇲🇦",
  "tunis": "🇹🇳",
  "djerba": "🇹🇳",
  "le caire": "🇪🇬",
  "cairo": "🇪🇬",
  "cap town": "🇿🇦",
  "le cap": "🇿🇦",
  "johannesburg": "🇿🇦",
  
  // Croatian
  "dubrovnik": "🇭🇷",
  "split": "🇭🇷",
  "zagreb": "🇭🇷",
  
  // Others European
  "amsterdam": "🇳🇱",
  "bruxelles": "🇧🇪",
  "brussels": "🇧🇪",
  "genève": "🇨🇭",
  "geneva": "🇨🇭",
  "zurich": "🇨🇭",
  "vienne": "🇦🇹",
  "vienna": "🇦🇹",
  "prague": "🇨🇿",
  "budapest": "🇭🇺",
  "varsovie": "🇵🇱",
  "warsaw": "🇵🇱",
  "cracovie": "🇵🇱",
  "krakow": "🇵🇱",
  "stockholm": "🇸🇪",
  "oslo": "🇳🇴",
  "copenhague": "🇩🇰",
  "copenhagen": "🇩🇰",
  "helsinki": "🇫🇮",
  "dublin": "🇮🇪",
  "reykjavik": "🇮🇸",
  "reykjavík": "🇮🇸",
  "monaco": "🇲🇨",
  
  // Americas
  "montréal": "🇨🇦",
  "montreal": "🇨🇦",
  "toronto": "🇨🇦",
  "vancouver": "🇨🇦",
  "mexico city": "🇲🇽",
  "cancun": "🇲🇽",
  "cancún": "🇲🇽",
  "rio de janeiro": "🇧🇷",
  "são paulo": "🇧🇷",
  "sao paulo": "🇧🇷",
  "buenos aires": "🇦🇷",
  "bogota": "🇨🇴",
  "bogotá": "🇨🇴",
  "lima": "🇵🇪",
  "santiago": "🇨🇱",
  "la havane": "🇨🇺",
  "havana": "🇨🇺",
  "punta cana": "🇩🇴",
  
  // Australia/Oceania
  "sydney": "🇦🇺",
  "melbourne": "🇦🇺",
  "auckland": "🇳🇿",
  "queenstown": "🇳🇿",
  "tahiti": "🇵🇫",
  "bora bora": "🇵🇫",
  "fidji": "🇫🇯",
  "fiji": "🇫🇯",
};

/**
 * Get emoji flag for a city or country name
 */
export function getEmojiForPlace(name: string): string {
  const normalized = name.toLowerCase().trim();
  return countryEmojis[normalized] || "✈️";
}
