-- Insert major cities from Africa (only if they don't already exist)
INSERT INTO cities (name, country, country_code)
SELECT * FROM (VALUES
-- Algérie
('Alger', 'Algérie', '🇩🇿'),
('Oran', 'Algérie', '🇩🇿'),
('Constantine', 'Algérie', '🇩🇿'),
('Annaba', 'Algérie', '🇩🇿'),
('Blida', 'Algérie', '🇩🇿'),
('Batna', 'Algérie', '🇩🇿'),
('Sétif', 'Algérie', '🇩🇿'),
('Sidi Bel Abbès', 'Algérie', '🇩🇿'),
('Tlemcen', 'Algérie', '🇩🇿'),
('Béjaïa', 'Algérie', '🇩🇿'),

-- Mali
('Bamako', 'Mali', '🇲🇱'),
('Sikasso', 'Mali', '🇲🇱'),
('Mopti', 'Mali', '🇲🇱'),
('Koutiala', 'Mali', '🇲🇱'),
('Kayes', 'Mali', '🇲🇱'),
('Ségou', 'Mali', '🇲🇱'),
('Gao', 'Mali', '🇲🇱'),
('Tombouctou', 'Mali', '🇲🇱'),
('Kidal', 'Mali', '🇲🇱'),
('San', 'Mali', '🇲🇱'),

-- Burkina Faso
('Ouagadougou', 'Burkina Faso', '🇧🇫'),
('Bobo-Dioulasso', 'Burkina Faso', '🇧🇫'),
('Koudougou', 'Burkina Faso', '🇧🇫'),
('Ouahigouya', 'Burkina Faso', '🇧🇫'),
('Banfora', 'Burkina Faso', '🇧🇫'),
('Dédougou', 'Burkina Faso', '🇧🇫'),
('Kaya', 'Burkina Faso', '🇧🇫'),
('Tenkodogo', 'Burkina Faso', '🇧🇫'),
('Fada N''Gourma', 'Burkina Faso', '🇧🇫'),
('Dori', 'Burkina Faso', '🇧🇫'),

-- Niger
('Niamey', 'Niger', '🇳🇪'),
('Zinder', 'Niger', '🇳🇪'),
('Maradi', 'Niger', '🇳🇪'),
('Agadez', 'Niger', '🇳🇪'),
('Tahoua', 'Niger', '🇳🇪'),
('Dosso', 'Niger', '🇳🇪'),
('Arlit', 'Niger', '🇳🇪'),
('Diffa', 'Niger', '🇳🇪'),
('Tillabéri', 'Niger', '🇳🇪'),
('Birni N''Konni', 'Niger', '🇳🇪'),

-- Tchad
('N''Djamena', 'Tchad', '🇹🇩'),
('Moundou', 'Tchad', '🇹🇩'),
('Sarh', 'Tchad', '🇹🇩'),
('Abéché', 'Tchad', '🇹🇩'),
('Kélo', 'Tchad', '🇹🇩'),
('Koumra', 'Tchad', '🇹🇩'),
('Pala', 'Tchad', '🇹🇩'),
('Am Timan', 'Tchad', '🇹🇩'),
('Bongor', 'Tchad', '🇹🇩'),
('Mongo', 'Tchad', '🇹🇩'),

-- Mauritanie
('Nouakchott', 'Mauritanie', '🇲🇷'),
('Nouadhibou', 'Mauritanie', '🇲🇷'),
('Néma', 'Mauritanie', '🇲🇷'),
('Kaédi', 'Mauritanie', '🇲🇷'),
('Rosso', 'Mauritanie', '🇲🇷'),
('Zouérate', 'Mauritanie', '🇲🇷'),
('Atar', 'Mauritanie', '🇲🇷'),
('Sélibaby', 'Mauritanie', '🇲🇷'),
('Kiffa', 'Mauritanie', '🇲🇷'),
('Aleg', 'Mauritanie', '🇲🇷'),

-- Guinée
('Conakry', 'Guinée', '🇬🇳'),
('Nzérékoré', 'Guinée', '🇬🇳'),
('Kankan', 'Guinée', '🇬🇳'),
('Kindia', 'Guinée', '🇬🇳'),
('Labé', 'Guinée', '🇬🇳'),
('Kamsar', 'Guinée', '🇬🇳'),
('Siguiri', 'Guinée', '🇬🇳'),
('Boké', 'Guinée', '🇬🇳'),
('Mamou', 'Guinée', '🇬🇳'),
('Dubréka', 'Guinée', '🇬🇳'),

-- Togo
('Lomé', 'Togo', '🇹🇬'),
('Sokodé', 'Togo', '🇹🇬'),
('Kara', 'Togo', '🇹🇬'),
('Kpalimé', 'Togo', '🇹🇬'),
('Atakpamé', 'Togo', '🇹🇬'),
('Dapaong', 'Togo', '🇹🇬'),
('Tsévié', 'Togo', '🇹🇬'),
('Aného', 'Togo', '🇹🇬'),
('Notsé', 'Togo', '🇹🇬'),
('Mango', 'Togo', '🇹🇬'),

-- Bénin
('Cotonou', 'Bénin', '🇧🇯'),
('Porto-Novo', 'Bénin', '🇧🇯'),
('Parakou', 'Bénin', '🇧🇯'),
('Djougou', 'Bénin', '🇧🇯'),
('Bohicon', 'Bénin', '🇧🇯'),
('Kandi', 'Bénin', '🇧🇯'),
('Lokossa', 'Bénin', '🇧🇯'),
('Ouidah', 'Bénin', '🇧🇯'),
('Abomey', 'Bénin', '🇧🇯'),
('Natitingou', 'Bénin', '🇧🇯'),

-- RD Congo
('Kinshasa', 'RD Congo', '🇨🇩'),
('Lubumbashi', 'RD Congo', '🇨🇩'),
('Mbuji-Mayi', 'RD Congo', '🇨🇩'),
('Kananga', 'RD Congo', '🇨🇩'),
('Kisangani', 'RD Congo', '🇨🇩'),
('Bukavu', 'RD Congo', '🇨🇩'),
('Goma', 'RD Congo', '🇨🇩'),
('Matadi', 'RD Congo', '🇨🇩'),
('Kolwezi', 'RD Congo', '🇨🇩'),
('Likasi', 'RD Congo', '🇨🇩'),

-- Congo
('Brazzaville', 'Congo', '🇨🇬'),
('Pointe-Noire', 'Congo', '🇨🇬'),
('Dolisie', 'Congo', '🇨🇬'),
('Nkayi', 'Congo', '🇨🇬'),
('Impfondo', 'Congo', '🇨🇬'),
('Ouesso', 'Congo', '🇨🇬'),
('Madingou', 'Congo', '🇨🇬'),
('Owando', 'Congo', '🇨🇬'),
('Sibiti', 'Congo', '🇨🇬'),
('Mossendjo', 'Congo', '🇨🇬'),

-- Gabon
('Libreville', 'Gabon', '🇬🇦'),
('Port-Gentil', 'Gabon', '🇬🇦'),
('Franceville', 'Gabon', '🇬🇦'),
('Oyem', 'Gabon', '🇬🇦'),
('Moanda', 'Gabon', '🇬🇦'),
('Mouila', 'Gabon', '🇬🇦'),
('Lambaréné', 'Gabon', '🇬🇦'),
('Tchibanga', 'Gabon', '🇬🇦'),
('Koulamoutou', 'Gabon', '🇬🇦'),
('Makokou', 'Gabon', '🇬🇦'),

-- Centrafrique
('Bangui', 'Centrafrique', '🇨🇫'),
('Bimbo', 'Centrafrique', '🇨🇫'),
('Berbérati', 'Centrafrique', '🇨🇫'),
('Carnot', 'Centrafrique', '🇨🇫'),
('Bambari', 'Centrafrique', '🇨🇫'),
('Bouar', 'Centrafrique', '🇨🇫'),
('Bossangoa', 'Centrafrique', '🇨🇫'),
('Bria', 'Centrafrique', '🇨🇫'),
('Bangassou', 'Centrafrique', '🇨🇫'),
('Nola', 'Centrafrique', '🇨🇦'),

-- Guinée équatoriale
('Malabo', 'Guinée équatoriale', '🇬🇶'),
('Bata', 'Guinée équatoriale', '🇬🇶'),
('Ebebiyin', 'Guinée équatoriale', '🇬🇶'),
('Aconibe', 'Guinée équatoriale', '🇬🇶'),
('Añisoc', 'Guinée équatoriale', '🇬🇶'),
('Luba', 'Guinée équatoriale', '🇬🇶'),
('Evinayong', 'Guinée équatoriale', '🇬🇶'),
('Mongomo', 'Guinée équatoriale', '🇬🇶'),
('Nsok-Nsomo', 'Guinée équatoriale', '🇬🇶'),
('Mikomeseng', 'Guinée équatoriale', '🇬🇶'),

-- Sierra Leone
('Freetown', 'Sierra Leone', '🇸🇱'),
('Bo', 'Sierra Leone', '🇸🇱'),
('Kenema', 'Sierra Leone', '🇸🇱'),
('Makeni', 'Sierra Leone', '🇸🇱'),
('Koidu', 'Sierra Leone', '🇸🇱'),
('Kabala', 'Sierra Leone', '🇸🇱'),
('Lunsar', 'Sierra Leone', '🇸🇱'),
('Port Loko', 'Sierra Leone', '🇸🇱'),
('Waterloo', 'Sierra Leone', '🇸🇱'),
('Bonthe', 'Sierra Leone', '🇸🇱'),

-- Liberia
('Monrovia', 'Liberia', '🇱🇷'),
('Gbarnga', 'Liberia', '🇱🇷'),
('Buchanan', 'Liberia', '🇱🇷'),
('Ganta', 'Liberia', '🇱🇷'),
('Kakata', 'Liberia', '🇱🇷'),
('Zwedru', 'Liberia', '🇱🇷'),
('Voinjama', 'Liberia', '🇱🇷'),
('Harper', 'Liberia', '🇱🇷'),
('Tubmanburg', 'Liberia', '🇱🇷'),
('Greenville', 'Liberia', '🇱🇷'),

-- Somalie
('Mogadiscio', 'Somalie', '🇸🇴'),
('Hargeisa', 'Somalie', '🇸🇴'),
('Berbera', 'Somalie', '🇸🇴'),
('Kismayo', 'Somalie', '🇸🇴'),
('Merca', 'Somalie', '🇸🇴'),
('Baidoa', 'Somalie', '🇸🇴'),
('Bosaso', 'Somalie', '🇸🇴'),
('Burao', 'Somalie', '🇸🇴'),
('Galkayo', 'Somalie', '🇸🇴'),
('Beledweyne', 'Somalie', '🇸🇴'),

-- Djibouti
('Djibouti', 'Djibouti', '🇩🇯'),
('Ali Sabieh', 'Djibouti', '🇩🇯'),
('Tadjourah', 'Djibouti', '🇩🇯'),
('Obock', 'Djibouti', '🇩🇯'),
('Dikhil', 'Djibouti', '🇩🇯'),
('Arta', 'Djibouti', '🇩🇯'),
('Holhol', 'Djibouti', '🇩🇯'),
('Balho', 'Djibouti', '🇩🇯'),
('Yoboki', 'Djibouti', '🇩🇯'),
('Randa', 'Djibouti', '🇩🇯'),

-- Érythrée
('Asmara', 'Érythrée', '🇪🇷'),
('Keren', 'Érythrée', '🇪🇷'),
('Massawa', 'Érythrée', '🇪🇷'),
('Assab', 'Érythrée', '🇪🇷'),
('Mendefera', 'Érythrée', '🇪🇷'),
('Barentu', 'Érythrée', '🇪🇷'),
('Adi Keyh', 'Érythrée', '🇪🇷'),
('Dekemhare', 'Érythrée', '🇪🇷'),
('Ak''ordat', 'Érythrée', '🇪🇷'),
('Adi Quala', 'Érythrée', '🇪🇷'),

-- Seychelles
('Victoria', 'Seychelles', '🇸🇨'),
('Anse Boileau', 'Seychelles', '🇸🇨'),
('Beau Vallon', 'Seychelles', '🇸🇨'),
('Cascade', 'Seychelles', '🇸🇨'),
('Takamaka', 'Seychelles', '🇸🇨'),
('Anse Royale', 'Seychelles', '🇸🇨'),
('Port Glaud', 'Seychelles', '🇸🇨'),
('La Digue', 'Seychelles', '🇸🇨'),
('Praslin', 'Seychelles', '🇸🇨'),
('Mahé', 'Seychelles', '🇸🇨'),

-- Comores
('Moroni', 'Comores', '🇰🇲'),
('Mutsamudu', 'Comores', '🇰🇲'),
('Fomboni', 'Comores', '🇰🇲'),
('Domoni', 'Comores', '🇰🇲'),
('Tsimbeo', 'Comores', '🇰🇲'),
('Mitsamiouli', 'Comores', '🇰🇲'),
('Ouani', 'Comores', '🇰🇲'),
('Sima', 'Comores', '🇰🇲'),
('Moya', 'Comores', '🇰🇲'),
('Bambao', 'Comores', '🇰🇲'),

-- Cap-Vert
('Praia', 'Cap-Vert', '🇨🇻'),
('Mindelo', 'Cap-Vert', '🇨🇻'),
('Santa Maria', 'Cap-Vert', '🇨🇻'),
('Assomada', 'Cap-Vert', '🇨🇻'),
('Tarrafal', 'Cap-Vert', '🇨🇻'),
('São Filipe', 'Cap-Vert', '🇨🇻'),
('Pedra Badejo', 'Cap-Vert', '🇨🇻'),
('Porto Novo', 'Cap-Vert', '🇨🇻'),
('Espargos', 'Cap-Vert', '🇨🇻'),
('Ribeira Grande', 'Cap-Vert', '🇨🇻'),

-- Sao Tomé-et-Principe
('São Tomé', 'Sao Tomé-et-Principe', '🇸🇹'),
('Santo António', 'Sao Tomé-et-Principe', '🇸🇹'),
('Neves', 'Sao Tomé-et-Principe', '🇸🇹'),
('Santana', 'Sao Tomé-et-Principe', '🇸🇹'),
('Trindade', 'Sao Tomé-et-Principe', '🇸🇹'),
('Santa Cruz', 'Sao Tomé-et-Principe', '🇸🇹'),
('Guadalupe', 'Sao Tomé-et-Principe', '🇸🇹'),
('Pantufo', 'Sao Tomé-et-Principe', '🇸🇹'),
('Angolares', 'Sao Tomé-et-Principe', '🇸🇹'),
('Porto Alegre', 'Sao Tomé-et-Principe', '🇸🇹'),

-- Malawi
('Lilongwe', 'Malawi', '🇲🇼'),
('Blantyre', 'Malawi', '🇲🇼'),
('Mzuzu', 'Malawi', '🇲🇼'),
('Zomba', 'Malawi', '🇲🇼'),
('Kasungu', 'Malawi', '🇲🇼'),
('Mangochi', 'Malawi', '🇲🇼'),
('Salima', 'Malawi', '🇲🇼'),
('Liwonde', 'Malawi', '🇲🇼'),
('Karonga', 'Malawi', '🇲🇼'),
('Dedza', 'Malawi', '🇲🇼'),

-- Lesotho
('Maseru', 'Lesotho', '🇱🇸'),
('Teyateyaneng', 'Lesotho', '🇱🇸'),
('Mafeteng', 'Lesotho', '🇱🇸'),
('Hlotse', 'Lesotho', '🇱🇸'),
('Mohale''s Hoek', 'Lesotho', '🇱🇸'),
('Maputsoe', 'Lesotho', '🇱🇸'),
('Qacha''s Nek', 'Lesotho', '🇱🇸'),
('Quthing', 'Lesotho', '🇱🇸'),
('Butha-Buthe', 'Lesotho', '🇱🇸'),
('Mokhotlong', 'Lesotho', '🇱🇸'),

-- Eswatini
('Mbabane', 'Eswatini', '🇸🇿'),
('Manzini', 'Eswatini', '🇸🇿'),
('Lobamba', 'Eswatini', '🇸🇿'),
('Big Bend', 'Eswatini', '🇸🇿'),
('Malkerns', 'Eswatini', '🇸🇿'),
('Nhlangano', 'Eswatini', '🇸🇿'),
('Siteki', 'Eswatini', '🇸🇿'),
('Piggs Peak', 'Eswatini', '🇸🇿'),
('Simunye', 'Eswatini', '🇸🇿'),
('Kwaluseni', 'Eswatini', '🇸🇿')
) AS v(name, country, country_code)
WHERE NOT EXISTS (
  SELECT 1 FROM cities WHERE cities.name = v.name AND cities.country = v.country
);