-- Insert major cities from Africa with comprehensive coverage
INSERT INTO cities (name, country, country_code) VALUES
-- Algérie (cities missing)
('Alger', 'Algérie', '🇩🇿'),
('Oran', 'Algérie', '🇩🇿'),
('Constantine', 'Algérie', '🇩🇿'),
('Annaba', 'Algérie', '🇩🇿'),
('Blida', 'Algérie', '🇩🇿'),
('Batna', 'Algérie', '🇩🇿'),
('Sétif', 'Algérie', '🇩🇿'),
('Sidi Bel Abbès', 'Algérie', '🇩🇿'),
('Tlemcen', 'Algérie', '🇩🇿'),
('Béjaïa', 'Algérie', '🇩🇿'),

-- Mali
('Bamako', 'Mali', '🇲🇱'),
('Sikasso', 'Mali', '🇲🇱'),
('Mopti', 'Mali', '🇲🇱'),
('Koutiala', 'Mali', '🇲🇱'),
('Kayes', 'Mali', '🇲🇱'),
('Ségou', 'Mali', '🇲🇱'),
('Gao', 'Mali', '🇲🇱'),
('Tombouctou', 'Mali', '🇲🇱'),
('Kidal', 'Mali', '🇲🇱'),
('San', 'Mali', '🇲🇱'),

-- Burkina Faso
('Ouagadougou', 'Burkina Faso', '🇧🇫'),
('Bobo-Dioulasso', 'Burkina Faso', '🇧🇫'),
('Koudougou', 'Burkina Faso', '🇧🇫'),
('Ouahigouya', 'Burkina Faso', '🇧🇫'),
('Banfora', 'Burkina Faso', '🇧🇫'),
('Dédougou', 'Burkina Faso', '🇧🇫'),
('Kaya', 'Burkina Faso', '🇧🇫'),
('Tenkodogo', 'Burkina Faso', '🇧🇫'),
('Fada N''Gourma', 'Burkina Faso', '🇧🇫'),
('Houndé', 'Burkina Faso', '🇧🇫'),

-- Niger
('Niamey', 'Niger', '🇳🇪'),
('Zinder', 'Niger', '🇳🇪'),
('Maradi', 'Niger', '🇳🇪'),
('Agadez', 'Niger', '🇳🇪'),
('Tahoua', 'Niger', '🇳🇪'),
('Dosso', 'Niger', '🇳🇪'),
('Diffa', 'Niger', '🇳🇪'),
('Arlit', 'Niger', '🇳🇪'),
('Tillabéri', 'Niger', '🇳🇪'),
('Gaya', 'Niger', '🇳🇪'),

-- Tchad
('N''Djamena', 'Tchad', '🇹🇩'),
('Moundou', 'Tchad', '🇹🇩'),
('Sarh', 'Tchad', '🇹🇩'),
('Abéché', 'Tchad', '🇹🇩'),
('Kelo', 'Tchad', '🇹🇩'),
('Koumra', 'Tchad', '🇹🇩'),
('Pala', 'Tchad', '🇹🇩'),
('Am Timan', 'Tchad', '🇹🇩'),
('Bongor', 'Tchad', '🇹🇩'),
('Mongo', 'Tchad', '🇹🇩'),

-- Soudan
('Khartoum', 'Soudan', '🇸🇩'),
('Omdurman', 'Soudan', '🇸🇩'),
('Port-Soudan', 'Soudan', '🇸🇩'),
('Kassala', 'Soudan', '🇸🇩'),
('El Obeid', 'Soudan', '🇸🇩'),
('Nyala', 'Soudan', '🇸🇩'),
('Wad Madani', 'Soudan', '🇸🇩'),
('El Fasher', 'Soudan', '🇸🇩'),
('El Gedaref', 'Soudan', '🇸🇩'),
('Atbara', 'Soudan', '🇸🇩'),

-- Érythrée
('Asmara', 'Érythrée', '🇪🇷'),
('Keren', 'Érythrée', '🇪🇷'),
('Massawa', 'Érythrée', '🇪🇷'),
('Assab', 'Érythrée', '🇪🇷'),
('Mendefera', 'Érythrée', '🇪🇷'),
('Barentu', 'Érythrée', '🇪🇷'),
('Adi Keyh', 'Érythrée', '🇪🇷'),
('Dekemhare', 'Érythrée', '🇪🇷'),
('Akorda', 'Érythrée', '🇪🇷'),
('Teseney', 'Érythrée', '🇪🇷'),

-- Djibouti
('Djibouti', 'Djibouti', '🇩🇯'),
('Ali Sabieh', 'Djibouti', '🇩🇯'),
('Tadjourah', 'Djibouti', '🇩🇯'),
('Obock', 'Djibouti', '🇩🇯'),
('Dikhil', 'Djibouti', '🇩🇯'),
('Arta', 'Djibouti', '🇩🇯'),
('Loyada', 'Djibouti', '🇩🇯'),
('Goubetto', 'Djibouti', '🇩🇯'),
('Balho', 'Djibouti', '🇩🇯'),
('Randa', 'Djibouti', '🇩🇯'),

-- Somalie
('Mogadiscio', 'Somalie', '🇸🇴'),
('Hargeisa', 'Somalie', '🇸🇴'),
('Berbera', 'Somalie', '🇸🇴'),
('Kismayo', 'Somalie', '🇸🇴'),
('Marka', 'Somalie', '🇸🇴'),
('Baidoa', 'Somalie', '🇸🇴'),
('Bosaso', 'Somalie', '🇸🇴'),
('Galkayo', 'Somalie', '🇸🇴'),
('Burco', 'Somalie', '🇸🇴'),
('Garowe', 'Somalie', '🇸🇴'),

-- Libye (additional)
('Tripoli', 'Libye', '🇱🇾'),
('Benghazi', 'Libye', '🇱🇾'),
('Misrata', 'Libye', '🇱🇾'),
('Tobrouk', 'Libye', '🇱🇾'),
('Sebha', 'Libye', '🇱🇾'),
('Zawiya', 'Libye', '🇱🇾'),
('Bayda', 'Libye', '🇱🇾'),
('Derna', 'Libye', '🇱🇾'),
('Zliten', 'Libye', '🇱🇾'),
('Zuwara', 'Libye', '🇱🇾'),

-- Nigéria
('Lagos', 'Nigéria', '🇳🇬'),
('Abuja', 'Nigéria', '🇳🇬'),
('Kano', 'Nigéria', '🇳🇬'),
('Ibadan', 'Nigéria', '🇳🇬'),
('Port Harcourt', 'Nigéria', '🇳🇬'),
('Kaduna', 'Nigéria', '🇳🇬'),
('Benin City', 'Nigéria', '🇳🇬'),
('Jos', 'Nigéria', '🇳🇬'),
('Enugu', 'Nigéria', '🇳🇬'),
('Zaria', 'Nigéria', '🇳🇬'),

-- Ghana
('Accra', 'Ghana', '🇬🇭'),
('Kumasi', 'Ghana', '🇬🇭'),
('Tamale', 'Ghana', '🇬🇭'),
('Sekondi-Takoradi', 'Ghana', '🇬🇭'),
('Cape Coast', 'Ghana', '🇬🇭'),
('Tema', 'Ghana', '🇬🇭'),
('Teshie', 'Ghana', '🇬🇭'),
('Obuasi', 'Ghana', '🇬🇭'),
('Koforidua', 'Ghana', '🇬🇭'),
('Ho', 'Ghana', '🇬🇭'),

-- Côte d''Ivoire
('Abidjan', 'Côte d''Ivoire', '🇨🇮'),
('Yamoussoukro', 'Côte d''Ivoire', '🇨🇮'),
('Bouaké', 'Côte d''Ivoire', '🇨🇮'),
('Daloa', 'Côte d''Ivoire', '🇨🇮'),
('San-Pédro', 'Côte d''Ivoire', '🇨🇮'),
('Korhogo', 'Côte d''Ivoire', '🇨🇮'),
('Man', 'Côte d''Ivoire', '🇨🇮'),
('Gagnoa', 'Côte d''Ivoire', '🇨🇮'),
('Divo', 'Côte d''Ivoire', '🇨🇮'),
('Soubré', 'Côte d''Ivoire', '🇨🇮'),

-- Sénégal
('Dakar', 'Sénégal', '🇸🇳'),
('Touba', 'Sénégal', '🇸🇳'),
('Thiès', 'Sénégal', '🇸🇳'),
('Saint-Louis', 'Sénégal', '🇸🇳'),
('Kaolack', 'Sénégal', '🇸🇳'),
('Ziguinchor', 'Sénégal', '🇸🇳'),
('Mbour', 'Sénégal', '🇸🇳'),
('Diourbel', 'Sénégal', '🇸🇳'),
('Louga', 'Sénégal', '🇸🇳'),
('Tambacounda', 'Sénégal', '🇸🇳'),

-- Cameroun
('Yaoundé', 'Cameroun', '🇨🇲'),
('Douala', 'Cameroun', '🇨🇲'),
('Garoua', 'Cameroun', '🇨🇲'),
('Bamenda', 'Cameroun', '🇨🇲'),
('Bafoussam', 'Cameroun', '🇨🇲'),
('Maroua', 'Cameroun', '🇨🇲'),
('Ngaoundéré', 'Cameroun', '🇨🇲'),
('Bertoua', 'Cameroun', '🇨🇲'),
('Buea', 'Cameroun', '🇨🇲'),
('Limbe', 'Cameroun', '🇨🇲'),

-- Kenya
('Nairobi', 'Kenya', '🇰🇪'),
('Mombasa', 'Kenya', '🇰🇪'),
('Kisumu', 'Kenya', '🇰🇪'),
('Nakuru', 'Kenya', '🇰🇪'),
('Eldoret', 'Kenya', '🇰🇪'),
('Thika', 'Kenya', '🇰🇪'),
('Malindi', 'Kenya', '🇰🇪'),
('Kitale', 'Kenya', '🇰🇪'),
('Garissa', 'Kenya', '🇰🇪'),
('Kakamega', 'Kenya', '🇰🇪'),

-- RD Congo
('Kinshasa', 'RD Congo', '🇨🇩'),
('Lubumbashi', 'RD Congo', '🇨🇩'),
('Mbuji-Mayi', 'RD Congo', '🇨🇩'),
('Kisangani', 'RD Congo', '🇨🇩'),
('Kananga', 'RD Congo', '🇨🇩'),
('Likasi', 'RD Congo', '🇨🇩'),
('Kolwezi', 'RD Congo', '🇨🇩'),
('Tshikapa', 'RD Congo', '🇨🇩'),
('Goma', 'RD Congo', '🇨🇩'),
('Bukavu', 'RD Congo', '🇨🇩'),

-- Congo
('Brazzaville', 'Congo', '🇨🇬'),
('Pointe-Noire', 'Congo', '🇨🇬'),
('Dolisie', 'Congo', '🇨🇬'),
('Nkayi', 'Congo', '🇨🇬'),
('Ouesso', 'Congo', '🇨🇬'),
('Owando', 'Congo', '🇨🇬'),
('Impfondo', 'Congo', '🇨🇬'),
('Sibiti', 'Congo', '🇨🇬'),
('Kinkala', 'Congo', '🇨🇬'),
('Madingou', 'Congo', '🇨🇬'),

-- Gabon
('Libreville', 'Gabon', '🇬🇦'),
('Port-Gentil', 'Gabon', '🇬🇦'),
('Franceville', 'Gabon', '🇬🇦'),
('Oyem', 'Gabon', '🇬🇦'),
('Moanda', 'Gabon', '🇬🇦'),
('Mouila', 'Gabon', '🇬🇦'),
('Lambaréné', 'Gabon', '🇬🇦'),
('Tchibanga', 'Gabon', '🇬🇦'),
('Koulamoutou', 'Gabon', '🇬🇦'),
('Makokou', 'Gabon', '🇬🇦'),

-- Guinée équatoriale
('Malabo', 'Guinée équatoriale', '🇬🇶'),
('Bata', 'Guinée équatoriale', '🇬🇶'),
('Ebebiyín', 'Guinée équatoriale', '🇬🇶'),
('Aconibe', 'Guinée équatoriale', '🇬🇶'),
('Añisoc', 'Guinée équatoriale', '🇬🇶'),
('Luba', 'Guinée équatoriale', '🇬🇶'),
('Evinayong', 'Guinée équatoriale', '🇬🇶'),
('Mongomo', 'Guinée équatoriale', '🇬🇶'),
('Nsok', 'Guinée équatoriale', '🇬🇶'),
('Riaba', 'Guinée équatoriale', '🇬🇶'),

-- Centrafrique
('Bangui', 'Centrafrique', '🇨🇫'),
('Bimbo', 'Centrafrique', '🇨🇫'),
('Berbérati', 'Centrafrique', '🇨🇫'),
('Carnot', 'Centrafrique', '🇨🇫'),
('Bambari', 'Centrafrique', '🇨🇫'),
('Bouar', 'Centrafrique', '🇨🇫'),
('Bossangoa', 'Centrafrique', '🇨🇫'),
('Bria', 'Centrafrique', '🇨🇫'),
('Bangassou', 'Centrafrique', '🇨🇫'),
('Nola', 'Centrafrique', '🇨🇫'),

-- Tanzanie
('Dar es Salaam', 'Tanzanie', '🇹🇿'),
('Dodoma', 'Tanzanie', '🇹🇿'),
('Mwanza', 'Tanzanie', '🇹🇿'),
('Zanzibar', 'Tanzanie', '🇹🇿'),
('Arusha', 'Tanzanie', '🇹🇿'),
('Mbeya', 'Tanzanie', '🇹🇿'),
('Morogoro', 'Tanzanie', '🇹🇿'),
('Tanga', 'Tanzanie', '🇹🇿'),
('Kigoma', 'Tanzanie', '🇹🇿'),
('Moshi', 'Tanzanie', '🇹🇿'),

-- Éthiopie
('Addis-Abeba', 'Éthiopie', '🇪🇹'),
('Dire Dawa', 'Éthiopie', '🇪🇹'),
('Mekele', 'Éthiopie', '🇪🇹'),
('Gondar', 'Éthiopie', '🇪🇹'),
('Bahir Dar', 'Éthiopie', '🇪🇹'),
('Awasa', 'Éthiopie', '🇪🇹'),
('Dessie', 'Éthiopie', '🇪🇹'),
('Jimma', 'Éthiopie', '🇪🇹'),
('Jijiga', 'Éthiopie', '🇪🇹'),
('Harar', 'Éthiopie', '🇪🇹'),

-- Afrique du Sud
('Johannesburg', 'Afrique du Sud', '🇿🇦'),
('Le Cap', 'Afrique du Sud', '🇿🇦'),
('Durban', 'Afrique du Sud', '🇿🇦'),
('Pretoria', 'Afrique du Sud', '🇿🇦'),
('Port Elizabeth', 'Afrique du Sud', '🇿🇦'),
('Bloemfontein', 'Afrique du Sud', '🇿🇦'),
('East London', 'Afrique du Sud', '🇿🇦'),
('Pietermaritzburg', 'Afrique du Sud', '🇿🇦'),
('Nelspruit', 'Afrique du Sud', '🇿🇦'),
('Kimberley', 'Afrique du Sud', '🇿🇦')
ON CONFLICT (id) DO NOTHING;