-- Insert major European and remaining world cities
INSERT INTO cities (name, country, country_code)
SELECT * FROM (VALUES
-- Europe - France (villes supplémentaires)
('Paris', 'France', '🇫🇷'),
('Lyon', 'France', '🇫🇷'),
('Marseille', 'France', '🇫🇷'),
('Toulouse', 'France', '🇫🇷'),
('Nice', 'France', '🇫🇷'),
('Nantes', 'France', '🇫🇷'),
('Strasbourg', 'France', '🇫🇷'),
('Montpellier', 'France', '🇫🇷'),
('Bordeaux', 'France', '🇫🇷'),
('Lille', 'France', '🇫🇷'),
('Rennes', 'France', '🇫🇷'),
('Reims', 'France', '🇫🇷'),
('Saint-Étienne', 'France', '🇫🇷'),
('Toulon', 'France', '🇫🇷'),
('Grenoble', 'France', '🇫🇷'),
('Dijon', 'France', '🇫🇷'),
('Angers', 'France', '🇫🇷'),
('Nîmes', 'France', '🇫🇷'),
('Villeurbanne', 'France', '🇫🇷'),
('Le Mans', 'France', '🇫🇷'),

-- Royaume-Uni
('Londres', 'Royaume-Uni', '🇬🇧'),
('Manchester', 'Royaume-Uni', '🇬🇧'),
('Birmingham', 'Royaume-Uni', '🇬🇧'),
('Liverpool', 'Royaume-Uni', '🇬🇧'),
('Leeds', 'Royaume-Uni', '🇬🇧'),
('Newcastle', 'Royaume-Uni', '🇬🇧'),
('Sheffield', 'Royaume-Uni', '🇬🇧'),
('Bristol', 'Royaume-Uni', '🇬🇧'),
('Édimbourg', 'Royaume-Uni', '🇬🇧'),
('Glasgow', 'Royaume-Uni', '🇬🇧'),
('Cardiff', 'Royaume-Uni', '🇬🇧'),
('Belfast', 'Royaume-Uni', '🇬🇧'),
('Brighton', 'Royaume-Uni', '🇬🇧'),
('Oxford', 'Royaume-Uni', '🇬🇧'),
('Cambridge', 'Royaume-Uni', '🇬🇧'),

-- Italie
('Rome', 'Italie', '🇮🇹'),
('Milan', 'Italie', '🇮🇹'),
('Naples', 'Italie', '🇮🇹'),
('Turin', 'Italie', '🇮🇹'),
('Palerme', 'Italie', '🇮🇹'),
('Gênes', 'Italie', '🇮🇹'),
('Bologne', 'Italie', '🇮🇹'),
('Florence', 'Italie', '🇮🇹'),
('Venise', 'Italie', '🇮🇹'),
('Vérone', 'Italie', '🇮🇹'),
('Catane', 'Italie', '🇮🇹'),
('Bari', 'Italie', '🇮🇹'),
('Pise', 'Italie', '🇮🇹'),
('Sienne', 'Italie', '🇮🇹'),
('Rimini', 'Italie', '🇮🇹'),

-- Espagne
('Madrid', 'Espagne', '🇪🇸'),
('Barcelone', 'Espagne', '🇪🇸'),
('Valence', 'Espagne', '🇪🇸'),
('Séville', 'Espagne', '🇪🇸'),
('Saragosse', 'Espagne', '🇪🇸'),
('Malaga', 'Espagne', '🇪🇸'),
('Murcie', 'Espagne', '🇪🇸'),
('Palma de Majorque', 'Espagne', '🇪🇸'),
('Bilbao', 'Espagne', '🇪🇸'),
('Grenade', 'Espagne', '🇪🇸'),
('Alicante', 'Espagne', '🇪🇸'),
('Cordoue', 'Espagne', '🇪🇸'),
('Salamanque', 'Espagne', '🇪🇸'),
('Tolède', 'Espagne', '🇪🇸'),
('Saint-Sébastien', 'Espagne', '🇪🇸'),

-- Portugal
('Lisbonne', 'Portugal', '🇵🇹'),
('Porto', 'Portugal', '🇵🇹'),
('Braga', 'Portugal', '🇵🇹'),
('Coimbra', 'Portugal', '🇵🇹'),
('Faro', 'Portugal', '🇵🇹'),
('Funchal', 'Portugal', '🇵🇹'),
('Setúbal', 'Portugal', '🇵🇹'),
('Aveiro', 'Portugal', '🇵🇹'),
('Évora', 'Portugal', '🇵🇹'),
('Sintra', 'Portugal', '🇵🇹'),

-- Allemagne
('Berlin', 'Allemagne', '🇩🇪'),
('Hambourg', 'Allemagne', '🇩🇪'),
('Munich', 'Allemagne', '🇩🇪'),
('Cologne', 'Allemagne', '🇩🇪'),
('Francfort', 'Allemagne', '🇩🇪'),
('Stuttgart', 'Allemagne', '🇩🇪'),
('Düsseldorf', 'Allemagne', '🇩🇪'),
('Dortmund', 'Allemagne', '🇩🇪'),
('Essen', 'Allemagne', '🇩🇪'),
('Leipzig', 'Allemagne', '🇩🇪'),
('Brême', 'Allemagne', '🇩🇪'),
('Dresde', 'Allemagne', '🇩🇪'),
('Hanovre', 'Allemagne', '🇩🇪'),
('Nuremberg', 'Allemagne', '🇩🇪'),
('Heidelberg', 'Allemagne', '🇩🇪'),

-- Pays-Bas
('Amsterdam', 'Pays-Bas', '🇳🇱'),
('Rotterdam', 'Pays-Bas', '🇳🇱'),
('La Haye', 'Pays-Bas', '🇳🇱'),
('Utrecht', 'Pays-Bas', '🇳🇱'),
('Eindhoven', 'Pays-Bas', '🇳🇱'),
('Tilburg', 'Pays-Bas', '🇳🇱'),
('Groningue', 'Pays-Bas', '🇳🇱'),
('Almere', 'Pays-Bas', '🇳🇱'),
('Maastricht', 'Pays-Bas', '🇳🇱'),
('Haarlem', 'Pays-Bas', '🇳🇱'),

-- Belgique
('Bruxelles', 'Belgique', '🇧🇪'),
('Anvers', 'Belgique', '🇧🇪'),
('Gand', 'Belgique', '🇧🇪'),
('Charleroi', 'Belgique', '🇧🇪'),
('Liège', 'Belgique', '🇧🇪'),
('Bruges', 'Belgique', '🇧🇪'),
('Namur', 'Belgique', '🇧🇪'),
('Louvain', 'Belgique', '🇧🇪'),
('Mons', 'Belgique', '🇧🇪'),
('Ostende', 'Belgique', '🇧🇪'),

-- Suisse
('Zurich', 'Suisse', '🇨🇭'),
('Genève', 'Suisse', '🇨🇭'),
('Bâle', 'Suisse', '🇨🇭'),
('Lausanne', 'Suisse', '🇨🇭'),
('Berne', 'Suisse', '🇨🇭'),
('Lucerne', 'Suisse', '🇨🇭'),
('Saint-Gall', 'Suisse', '🇨🇭'),
('Lugano', 'Suisse', '🇨🇭'),
('Interlaken', 'Suisse', '🇨🇭'),
('Zermatt', 'Suisse', '🇨🇭'),

-- Autriche
('Vienne', 'Autriche', '🇦🇹'),
('Graz', 'Autriche', '🇦🇹'),
('Linz', 'Autriche', '🇦🇹'),
('Salzbourg', 'Autriche', '🇦🇹'),
('Innsbruck', 'Autriche', '🇦🇹'),
('Klagenfurt', 'Autriche', '🇦🇹'),
('Villach', 'Autriche', '🇦🇹'),
('Wels', 'Autriche', '🇦🇹'),
('Sankt Pölten', 'Autriche', '🇦🇹'),
('Hallstatt', 'Autriche', '🇦🇹'),

-- Tchéquie
('Prague', 'Tchéquie', '🇨🇿'),
('Brno', 'Tchéquie', '🇨🇿'),
('Ostrava', 'Tchéquie', '🇨🇿'),
('Plzeň', 'Tchéquie', '🇨🇿'),
('Liberec', 'Tchéquie', '🇨🇿'),
('Olomouc', 'Tchéquie', '🇨🇿'),
('České Budějovice', 'Tchéquie', '🇨🇿'),
('Hradec Králové', 'Tchéquie', '🇨🇿'),
('Karlovy Vary', 'Tchéquie', '🇨🇿'),
('Český Krumlov', 'Tchéquie', '🇨🇿'),

-- Hongrie
('Budapest', 'Hongrie', '🇭🇺'),
('Debrecen', 'Hongrie', '🇭🇺'),
('Szeged', 'Hongrie', '🇭🇺'),
('Miskolc', 'Hongrie', '🇭🇺'),
('Pécs', 'Hongrie', '🇭🇺'),
('Győr', 'Hongrie', '🇭🇺'),
('Nyíregyháza', 'Hongrie', '🇭🇺'),
('Kecskemét', 'Hongrie', '🇭🇺'),
('Székesfehérvár', 'Hongrie', '🇭🇺'),
('Eger', 'Hongrie', '🇭🇺'),

-- Pologne
('Varsovie', 'Pologne', '🇵🇱'),
('Cracovie', 'Pologne', '🇵🇱'),
('Łódź', 'Pologne', '🇵🇱'),
('Wrocław', 'Pologne', '🇵🇱'),
('Poznań', 'Pologne', '🇵🇱'),
('Gdańsk', 'Pologne', '🇵🇱'),
('Szczecin', 'Pologne', '🇵🇱'),
('Bydgoszcz', 'Pologne', '🇵🇱'),
('Lublin', 'Pologne', '🇵🇱'),
('Katowice', 'Pologne', '🇵🇱'),

-- Grèce
('Athènes', 'Grèce', '🇬🇷'),
('Thessalonique', 'Grèce', '🇬🇷'),
('Patras', 'Grèce', '🇬🇷'),
('Santorin', 'Grèce', '🇬🇷'),
('Mykonos', 'Grèce', '🇬🇷'),
('Rhodes', 'Grèce', '🇬🇷'),
('Corfou', 'Grèce', '🇬🇷'),
('Crète', 'Grèce', '🇬🇷'),
('Héraklion', 'Grèce', '🇬🇷'),
('Delphes', 'Grèce', '🇬🇷'),

-- Turquie
('Istanbul', 'Turquie', '🇹🇷'),
('Ankara', 'Turquie', '🇹🇷'),
('Izmir', 'Turquie', '🇹🇷'),
('Bursa', 'Turquie', '🇹🇷'),
('Antalya', 'Turquie', '🇹🇷'),
('Cappadoce', 'Turquie', '🇹🇷'),
('Bodrum', 'Turquie', '🇹🇷'),
('Marmaris', 'Turquie', '🇹🇷'),
('Kusadasi', 'Turquie', '🇹🇷'),
('Pamukkale', 'Turquie', '🇹🇷'),

-- Danemark
('Copenhague', 'Danemark', '🇩🇰'),
('Aarhus', 'Danemark', '🇩🇰'),
('Odense', 'Danemark', '🇩🇰'),
('Aalborg', 'Danemark', '🇩🇰'),
('Esbjerg', 'Danemark', '🇩🇰'),
('Randers', 'Danemark', '🇩🇰'),
('Kolding', 'Danemark', '🇩🇰'),
('Horsens', 'Danemark', '🇩🇰'),
('Vejle', 'Danemark', '🇩🇰'),
('Roskilde', 'Danemark', '🇩🇰'),

-- Suède
('Stockholm', 'Suède', '🇸🇪'),
('Göteborg', 'Suède', '🇸🇪'),
('Malmö', 'Suède', '🇸🇪'),
('Uppsala', 'Suède', '🇸🇪'),
('Linköping', 'Suède', '🇸🇪'),
('Västerås', 'Suède', '🇸🇪'),
('Örebro', 'Suède', '🇸🇪'),
('Norrköping', 'Suède', '🇸🇪'),
('Helsingborg', 'Suède', '🇸🇪'),
('Jönköping', 'Suède', '🇸🇪'),

-- Norvège
('Oslo', 'Norvège', '🇳🇴'),
('Bergen', 'Norvège', '🇳🇴'),
('Trondheim', 'Norvège', '🇳🇴'),
('Stavanger', 'Norvège', '🇳🇴'),
('Tromsø', 'Norvège', '🇳🇴'),
('Drammen', 'Norvège', '🇳🇴'),
('Kristiansand', 'Norvège', '🇳🇴'),
('Ålesund', 'Norvège', '🇳🇴'),
('Bodø', 'Norvège', '🇳🇴'),
('Fredrikstad', 'Norvège', '🇳🇴'),

-- Finlande
('Helsinki', 'Finlande', '🇫🇮'),
('Espoo', 'Finlande', '🇫🇮'),
('Tampere', 'Finlande', '🇫🇮'),
('Vantaa', 'Finlande', '🇫🇮'),
('Oulu', 'Finlande', '🇫🇮'),
('Turku', 'Finlande', '🇫🇮'),
('Jyväskylä', 'Finlande', '🇫🇮'),
('Lahti', 'Finlande', '🇫🇮'),
('Kuopio', 'Finlande', '🇫🇮'),
('Rovaniemi', 'Finlande', '🇫🇮'),

-- Islande
('Reykjavik', 'Islande', '🇮🇸'),
('Akureyri', 'Islande', '🇮🇸'),
('Keflavík', 'Islande', '🇮🇸'),
('Reykjanesbær', 'Islande', '🇮🇸'),
('Hafnarfjörður', 'Islande', '🇮🇸'),
('Kópavogur', 'Islande', '🇮🇸'),
('Selfoss', 'Islande', '🇮🇸'),
('Egilsstaðir', 'Islande', '🇮🇸'),
('Ísafjörður', 'Islande', '🇮🇸'),
('Húsavík', 'Islande', '🇮🇸'),

-- Irlande
('Dublin', 'Irlande', '🇮🇪'),
('Cork', 'Irlande', '🇮🇪'),
('Galway', 'Irlande', '🇮🇪'),
('Limerick', 'Irlande', '🇮🇪'),
('Waterford', 'Irlande', '🇮🇪'),
('Killarney', 'Irlande', '🇮🇪'),
('Kilkenny', 'Irlande', '🇮🇪'),
('Sligo', 'Irlande', '🇮🇪'),
('Drogheda', 'Irlande', '🇮🇪'),
('Dundalk', 'Irlande', '🇮🇪'),

-- Croatie
('Zagreb', 'Croatie', '🇭🇷'),
('Split', 'Croatie', '🇭🇷'),
('Rijeka', 'Croatie', '🇭🇷'),
('Dubrovnik', 'Croatie', '🇭🇷'),
('Zadar', 'Croatie', '🇭🇷'),
('Pula', 'Croatie', '🇭🇷'),
('Rovinj', 'Croatie', '🇭🇷'),
('Osijek', 'Croatie', '🇭🇷'),
('Šibenik', 'Croatie', '🇭🇷'),
('Hvar', 'Croatie', '🇭🇷'),

-- Serbie
('Belgrade', 'Serbie', '🇷🇸'),
('Novi Sad', 'Serbie', '🇷🇸'),
('Niš', 'Serbie', '🇷🇸'),
('Kragujevac', 'Serbie', '🇷🇸'),
('Subotica', 'Serbie', '🇷🇸'),
('Zrenjanin', 'Serbie', '🇷🇸'),
('Pančevo', 'Serbie', '🇷🇸'),
('Čačak', 'Serbie', '🇷🇸'),
('Kraljevo', 'Serbie', '🇷🇸'),
('Smederevo', 'Serbie', '🇷🇸'),

-- Roumanie
('Bucarest', 'Roumanie', '🇷🇴'),
('Cluj-Napoca', 'Roumanie', '🇷🇴'),
('Timișoara', 'Roumanie', '🇷🇴'),
('Iași', 'Roumanie', '🇷🇴'),
('Constanța', 'Roumanie', '🇷🇴'),
('Craiova', 'Roumanie', '🇷🇴'),
('Brașov', 'Roumanie', '🇷🇴'),
('Galați', 'Roumanie', '🇷🇴'),
('Ploiești', 'Roumanie', '🇷🇴'),
('Sibiu', 'Roumanie', '🇷🇴'),

-- Bulgarie
('Sofia', 'Bulgarie', '🇧🇬'),
('Plovdiv', 'Bulgarie', '🇧🇬'),
('Varna', 'Bulgarie', '🇧🇬'),
('Burgas', 'Bulgarie', '🇧🇬'),
('Ruse', 'Bulgarie', '🇧🇬'),
('Stara Zagora', 'Bulgarie', '🇧🇬'),
('Pleven', 'Bulgarie', '🇧🇬'),
('Sliven', 'Bulgarie', '🇧🇬'),
('Veliko Tarnovo', 'Bulgarie', '🇧🇬'),
('Bansko', 'Bulgarie', '🇧🇬'),

-- Slovénie
('Ljubljana', 'Slovénie', '🇸🇮'),
('Maribor', 'Slovénie', '🇸🇮'),
('Celje', 'Slovénie', '🇸🇮'),
('Kranj', 'Slovénie', '🇸🇮'),
('Bled', 'Slovénie', '🇸🇮'),
('Piran', 'Slovénie', '🇸🇮'),
('Koper', 'Slovénie', '🇸🇮'),
('Novo Mesto', 'Slovénie', '🇸🇮'),
('Ptuj', 'Slovénie', '🇸🇮'),
('Postojna', 'Slovénie', '🇸🇮'),

-- Slovaquie
('Bratislava', 'Slovaquie', '🇸🇰'),
('Košice', 'Slovaquie', '🇸🇰'),
('Prešov', 'Slovaquie', '🇸🇰'),
('Žilina', 'Slovaquie', '🇸🇰'),
('Banská Bystrica', 'Slovaquie', '🇸🇰'),
('Nitra', 'Slovaquie', '🇸🇰'),
('Trnava', 'Slovaquie', '🇸🇰'),
('Martin', 'Slovaquie', '🇸🇰'),
('Trenčín', 'Slovaquie', '🇸🇰'),
('Poprad', 'Slovaquie', '🇸🇰'),

-- Russie (principales villes)
('Moscou', 'Russie', '🇷🇺'),
('Saint-Pétersbourg', 'Russie', '🇷🇺'),
('Novossibirsk', 'Russie', '🇷🇺'),
('Ekaterinbourg', 'Russie', '🇷🇺'),
('Kazan', 'Russie', '🇷🇺'),
('Nijni Novgorod', 'Russie', '🇷🇺'),
('Tcheliabinsk', 'Russie', '🇷🇺'),
('Samara', 'Russie', '🇷🇺'),
('Omsk', 'Russie', '🇷🇺'),
('Rostov-sur-le-Don', 'Russie', '🇷🇺'),

-- Ukraine
('Kiev', 'Ukraine', '🇺🇦'),
('Kharkiv', 'Ukraine', '🇺🇦'),
('Odessa', 'Ukraine', '🇺🇦'),
('Dnipro', 'Ukraine', '🇺🇦'),
('Donetsk', 'Ukraine', '🇺🇦'),
('Zaporijia', 'Ukraine', '🇺🇦'),
('Lviv', 'Ukraine', '🇺🇦'),
('Kryvyi Rih', 'Ukraine', '🇺🇦'),
('Mykolaïv', 'Ukraine', '🇺🇦'),
('Marioupol', 'Ukraine', '🇺🇦'),

-- Pays Baltes
('Tallinn', 'Estonie', '🇪🇪'),
('Tartu', 'Estonie', '🇪🇪'),
('Narva', 'Estonie', '🇪🇪'),
('Pärnu', 'Estonie', '🇪🇪'),
('Riga', 'Lettonie', '🇱🇻'),
('Daugavpils', 'Lettonie', '🇱🇻'),
('Liepāja', 'Lettonie', '🇱🇻'),
('Jelgava', 'Lettonie', '🇱🇻'),
('Vilnius', 'Lituanie', '🇱🇹'),
('Kaunas', 'Lituanie', '🇱🇹'),
('Klaipėda', 'Lituanie', '🇱🇹'),
('Šiauliai', 'Lituanie', '🇱🇹'),

-- Amérique Centrale & Caraïbes
('La Havane', 'Cuba', '🇨🇺'),
('Santiago de Cuba', 'Cuba', '🇨🇺'),
('Varadero', 'Cuba', '🇨🇺'),
('Trinidad', 'Cuba', '🇨🇺'),
('Cienfuegos', 'Cuba', '🇨🇺'),
('Saint-Domingue', 'République Dominicaine', '🇩🇴'),
('Punta Cana', 'République Dominicaine', '🇩🇴'),
('Puerto Plata', 'République Dominicaine', '🇩🇴'),
('Kingston', 'Jamaïque', '🇯🇲'),
('Montego Bay', 'Jamaïque', '🇯🇲'),
('San José', 'Costa Rica', '🇨🇷'),
('Manuel Antonio', 'Costa Rica', '🇨🇷'),
('Tamarindo', 'Costa Rica', '🇨🇷'),
('Panama City', 'Panama', '🇵🇦'),
('Bocas del Toro', 'Panama', '🇵🇦'),
('San Salvador', 'Salvador', '🇸🇻'),
('Guatemala City', 'Guatemala', '🇬🇹'),
('Antigua', 'Guatemala', '🇬🇹'),
('Tegucigalpa', 'Honduras', '🇭🇳'),
('Managua', 'Nicaragua', '🇳🇮'),

-- Pacifique
('Suva', 'Fidji', '🇫🇯'),
('Nadi', 'Fidji', '🇫🇯'),
('Papeete', 'Polynésie française', '🇵🇫'),
('Bora Bora', 'Polynésie française', '🇵🇫'),
('Moorea', 'Polynésie française', '🇵🇫'),
('Nouméa', 'Nouvelle-Calédonie', '🇳🇨'),
('Port Moresby', 'Papouasie-Nouvelle-Guinée', '🇵🇬'),
('Apia', 'Samoa', '🇼🇸'),
('Port-Vila', 'Vanuatu', '🇻🇺'),
('Honiara', 'Îles Salomon', '🇸🇧'),

-- Guyanes
('Georgetown', 'Guyana', '🇬🇾'),
('Paramaribo', 'Suriname', '🇸🇷'),
('Cayenne', 'Guyane française', '🇬🇫'),

-- Amérique Centrale additionnelle
('Belize City', 'Belize', '🇧🇿'),
('San Pedro', 'Belize', '🇧🇿')
) AS v(name, country, country_code)
WHERE NOT EXISTS (
  SELECT 1 FROM cities WHERE cities.name = v.name AND cities.country = v.country
);