-- Insert major cities from Asia, Americas and additional European cities
INSERT INTO cities (name, country, country_code)
SELECT * FROM (VALUES
-- Asie - Chine
('Shanghai', 'Chine', '🇨🇳'),
('Pékin', 'Chine', '🇨🇳'),
('Guangzhou', 'Chine', '🇨🇳'),
('Shenzhen', 'Chine', '🇨🇳'),
('Chengdu', 'Chine', '🇨🇳'),
('Chongqing', 'Chine', '🇨🇳'),
('Tianjin', 'Chine', '🇨🇳'),
('Wuhan', 'Chine', '🇨🇳'),
('Xi''an', 'Chine', '🇨🇳'),
('Hangzhou', 'Chine', '🇨🇳'),
('Nanjing', 'Chine', '🇨🇳'),
('Suzhou', 'Chine', '🇨🇳'),
('Qingdao', 'Chine', '🇨🇳'),
('Dalian', 'Chine', '🇨🇳'),
('Kunming', 'Chine', '🇨🇳'),

-- Hong Kong & Macao
('Hong Kong', 'Hong Kong', '🇭🇰'),
('Kowloon', 'Hong Kong', '🇭🇰'),
('Macao', 'Macao', '🇲🇴'),

-- Japon
('Tokyo', 'Japon', '🇯🇵'),
('Yokohama', 'Japon', '🇯🇵'),
('Osaka', 'Japon', '🇯🇵'),
('Nagoya', 'Japon', '🇯🇵'),
('Sapporo', 'Japon', '🇯🇵'),
('Fukuoka', 'Japon', '🇯🇵'),
('Kobe', 'Japon', '🇯🇵'),
('Kyoto', 'Japon', '🇯🇵'),
('Hiroshima', 'Japon', '🇯🇵'),
('Nara', 'Japon', '🇯🇵'),

-- Corée du Sud
('Séoul', 'Corée du Sud', '🇰🇷'),
('Busan', 'Corée du Sud', '🇰🇷'),
('Incheon', 'Corée du Sud', '🇰🇷'),
('Daegu', 'Corée du Sud', '🇰🇷'),
('Daejeon', 'Corée du Sud', '🇰🇷'),
('Gwangju', 'Corée du Sud', '🇰🇷'),
('Suwon', 'Corée du Sud', '🇰🇷'),
('Ulsan', 'Corée du Sud', '🇰🇷'),
('Changwon', 'Corée du Sud', '🇰🇷'),
('Jeju', 'Corée du Sud', '🇰🇷'),

-- Inde
('Mumbai', 'Inde', '🇮🇳'),
('Delhi', 'Inde', '🇮🇳'),
('Bangalore', 'Inde', '🇮🇳'),
('Hyderabad', 'Inde', '🇮🇳'),
('Chennai', 'Inde', '🇮🇳'),
('Kolkata', 'Inde', '🇮🇳'),
('Pune', 'Inde', '🇮🇳'),
('Jaipur', 'Inde', '🇮🇳'),
('Agra', 'Inde', '🇮🇳'),
('Goa', 'Inde', '🇮🇳'),

-- Thaïlande
('Bangkok', 'Thaïlande', '🇹🇭'),
('Chiang Mai', 'Thaïlande', '🇹🇭'),
('Phuket', 'Thaïlande', '🇹🇭'),
('Pattaya', 'Thaïlande', '🇹🇭'),
('Koh Samui', 'Thaïlande', '🇹🇭'),
('Krabi', 'Thaïlande', '🇹🇭'),
('Hua Hin', 'Thaïlande', '🇹🇭'),
('Ayutthaya', 'Thaïlande', '🇹🇭'),
('Khon Kaen', 'Thaïlande', '🇹🇭'),
('Udon Thani', 'Thaïlande', '🇹🇭'),

-- Vietnam
('Hô Chi Minh', 'Vietnam', '🇻🇳'),
('Hanoi', 'Vietnam', '🇻🇳'),
('Da Nang', 'Vietnam', '🇻🇳'),
('Haiphong', 'Vietnam', '🇻🇳'),
('Hoi An', 'Vietnam', '🇻🇳'),
('Hue', 'Vietnam', '🇻🇳'),
('Nha Trang', 'Vietnam', '🇻🇳'),
('Can Tho', 'Vietnam', '🇻🇳'),
('Vung Tau', 'Vietnam', '🇻🇳'),
('Da Lat', 'Vietnam', '🇻🇳'),

-- Indonésie
('Jakarta', 'Indonésie', '🇮🇩'),
('Surabaya', 'Indonésie', '🇮🇩'),
('Bandung', 'Indonésie', '🇮🇩'),
('Medan', 'Indonésie', '🇮🇩'),
('Bali', 'Indonésie', '🇮🇩'),
('Yogyakarta', 'Indonésie', '🇮🇩'),
('Semarang', 'Indonésie', '🇮🇩'),
('Makassar', 'Indonésie', '🇮🇩'),
('Palembang', 'Indonésie', '🇮🇩'),
('Lombok', 'Indonésie', '🇮🇩'),

-- Malaisie
('Kuala Lumpur', 'Malaisie', '🇲🇾'),
('George Town', 'Malaisie', '🇲🇾'),
('Ipoh', 'Malaisie', '🇲🇾'),
('Johor Bahru', 'Malaisie', '🇲🇾'),
('Langkawi', 'Malaisie', '🇲🇾'),
('Malacca', 'Malaisie', '🇲🇾'),
('Kota Kinabalu', 'Malaisie', '🇲🇾'),
('Kuching', 'Malaisie', '🇲🇾'),
('Penang', 'Malaisie', '🇲🇾'),
('Shah Alam', 'Malaisie', '🇲🇾'),

-- Singapour
('Singapour', 'Singapour', '🇸🇬'),

-- Philippines
('Manille', 'Philippines', '🇵🇭'),
('Quezon City', 'Philippines', '🇵🇭'),
('Davao', 'Philippines', '🇵🇭'),
('Cebu', 'Philippines', '🇵🇭'),
('Boracay', 'Philippines', '🇵🇭'),
('Makati', 'Philippines', '🇵🇭'),
('Palawan', 'Philippines', '🇵🇭'),
('Baguio', 'Philippines', '🇵🇭'),
('Iloilo', 'Philippines', '🇵🇭'),
('Zamboanga', 'Philippines', '🇵🇭'),

-- Cambodge
('Phnom Penh', 'Cambodge', '🇰🇭'),
('Siem Reap', 'Cambodge', '🇰🇭'),
('Sihanoukville', 'Cambodge', '🇰🇭'),
('Battambang', 'Cambodge', '🇰🇭'),
('Kampot', 'Cambodge', '🇰🇭'),
('Kep', 'Cambodge', '🇰🇭'),
('Kampong Cham', 'Cambodge', '🇰🇭'),
('Pursat', 'Cambodge', '🇰🇭'),
('Takeo', 'Cambodge', '🇰🇭'),
('Kratié', 'Cambodge', '🇰🇭'),

-- Laos
('Vientiane', 'Laos', '🇱🇦'),
('Luang Prabang', 'Laos', '🇱🇦'),
('Paksé', 'Laos', '🇱🇦'),
('Savannakhet', 'Laos', '🇱🇦'),
('Vang Vieng', 'Laos', '🇱🇦'),
('Thakhek', 'Laos', '🇱🇦'),
('Phonsavan', 'Laos', '🇱🇦'),
('Muang Xai', 'Laos', '🇱🇦'),
('Luang Namtha', 'Laos', '🇱🇦'),
('Champasak', 'Laos', '🇱🇦'),

-- Myanmar
('Yangon', 'Myanmar', '🇲🇲'),
('Mandalay', 'Myanmar', '🇲🇲'),
('Bagan', 'Myanmar', '🇲🇲'),
('Naypyidaw', 'Myanmar', '🇲🇲'),
('Mawlamyine', 'Myanmar', '🇲🇲'),
('Inle Lake', 'Myanmar', '🇲🇲'),
('Taunggyi', 'Myanmar', '🇲🇲'),
('Sittwe', 'Myanmar', '🇲🇲'),
('Pathein', 'Myanmar', '🇲🇲'),
('Myitkyina', 'Myanmar', '🇲🇲'),

-- Pakistan
('Karachi', 'Pakistan', '🇵🇰'),
('Lahore', 'Pakistan', '🇵🇰'),
('Islamabad', 'Pakistan', '🇵🇰'),
('Rawalpindi', 'Pakistan', '🇵🇰'),
('Faisalabad', 'Pakistan', '🇵🇰'),
('Multan', 'Pakistan', '🇵🇰'),
('Peshawar', 'Pakistan', '🇵🇰'),
('Quetta', 'Pakistan', '🇵🇰'),
('Sialkot', 'Pakistan', '🇵🇰'),
('Gujranwala', 'Pakistan', '🇵🇰'),

-- Bangladesh
('Dhaka', 'Bangladesh', '🇧🇩'),
('Chittagong', 'Bangladesh', '🇧🇩'),
('Khulna', 'Bangladesh', '🇧🇩'),
('Rajshahi', 'Bangladesh', '🇧🇩'),
('Sylhet', 'Bangladesh', '🇧🇩'),
('Rangpur', 'Bangladesh', '🇧🇩'),
('Barisal', 'Bangladesh', '🇧🇩'),
('Cox''s Bazar', 'Bangladesh', '🇧🇩'),
('Mymensingh', 'Bangladesh', '🇧🇩'),
('Comilla', 'Bangladesh', '🇧🇩'),

-- Sri Lanka
('Colombo', 'Sri Lanka', '🇱🇰'),
('Kandy', 'Sri Lanka', '🇱🇰'),
('Galle', 'Sri Lanka', '🇱🇰'),
('Negombo', 'Sri Lanka', '🇱🇰'),
('Jaffna', 'Sri Lanka', '🇱🇰'),
('Trincomalee', 'Sri Lanka', '🇱🇰'),
('Batticaloa', 'Sri Lanka', '🇱🇰'),
('Anuradhapura', 'Sri Lanka', '🇱🇰'),
('Polonnaruwa', 'Sri Lanka', '🇱🇰'),
('Ella', 'Sri Lanka', '🇱🇰'),

-- Népal
('Katmandou', 'Népal', '🇳🇵'),
('Pokhara', 'Népal', '🇳🇵'),
('Lalitpur', 'Népal', '🇳🇵'),
('Bhaktapur', 'Népal', '🇳🇵'),
('Biratnagar', 'Népal', '🇳🇵'),
('Bharatpur', 'Népal', '🇳🇵'),
('Dharan', 'Népal', '🇳🇵'),
('Butwal', 'Népal', '🇳🇵'),
('Janakpur', 'Népal', '🇳🇵'),
('Lumbini', 'Népal', '🇳🇵'),

-- Maldives
('Malé', 'Maldives', '🇲🇻'),
('Addu City', 'Maldives', '🇲🇻'),
('Fuvahmulah', 'Maldives', '🇲🇻'),
('Kulhudhuffushi', 'Maldives', '🇲🇻'),
('Thinadhoo', 'Maldives', '🇲🇻'),
('Hithadhoo', 'Maldives', '🇲🇻'),
('Hulhumale', 'Maldives', '🇲🇻'),
('Maafushi', 'Maldives', '🇲🇻'),
('Guraidhoo', 'Maldives', '🇲🇻'),
('Thulusdhoo', 'Maldives', '🇲🇻'),

-- Émirats Arabes Unis
('Dubaï', 'Émirats arabes unis', '🇦🇪'),
('Abu Dhabi', 'Émirats arabes unis', '🇦🇪'),
('Sharjah', 'Émirats arabes unis', '🇦🇪'),
('Ajman', 'Émirats arabes unis', '🇦🇪'),
('Ras al-Khaimah', 'Émirats arabes unis', '🇦🇪'),
('Fujairah', 'Émirats arabes unis', '🇦🇪'),
('Umm al-Quwain', 'Émirats arabes unis', '🇦🇪'),
('Al Ain', 'Émirats arabes unis', '🇦🇪'),
('Dibba', 'Émirats arabes unis', '🇦🇪'),
('Khor Fakkan', 'Émirats arabes unis', '🇦🇪'),

-- Arabie Saoudite
('Riyad', 'Arabie Saoudite', '🇸🇦'),
('Djeddah', 'Arabie Saoudite', '🇸🇦'),
('La Mecque', 'Arabie Saoudite', '🇸🇦'),
('Médine', 'Arabie Saoudite', '🇸🇦'),
('Dammam', 'Arabie Saoudite', '🇸🇦'),
('Tabuk', 'Arabie Saoudite', '🇸🇦'),
('Khobar', 'Arabie Saoudite', '🇸🇦'),
('Taif', 'Arabie Saoudite', '🇸🇦'),
('Jubail', 'Arabie Saoudite', '🇸🇦'),
('Buraidah', 'Arabie Saoudite', '🇸🇦'),

-- Qatar
('Doha', 'Qatar', '🇶🇦'),
('Al Wakrah', 'Qatar', '🇶🇦'),
('Al Rayyan', 'Qatar', '🇶🇦'),
('Umm Salal', 'Qatar', '🇶🇦'),
('Al Khor', 'Qatar', '🇶🇦'),
('Lusail', 'Qatar', '🇶🇦'),
('Mesaieed', 'Qatar', '🇶🇦'),
('Dukhan', 'Qatar', '🇶🇦'),
('Al Shamal', 'Qatar', '🇶🇦'),
('Al Daayen', 'Qatar', '🇶🇦'),

-- Oman
('Mascate', 'Oman', '🇴🇲'),
('Salalah', 'Oman', '🇴🇲'),
('Sohar', 'Oman', '🇴🇲'),
('Nizwa', 'Oman', '🇴🇲'),
('Sur', 'Oman', '🇴🇲'),
('Ibri', 'Oman', '🇴🇲'),
('Buraimi', 'Oman', '🇴🇲'),
('Bahla', 'Oman', '🇴🇲'),
('Rustaq', 'Oman', '🇴🇲'),
('Khasab', 'Oman', '🇴🇲'),

-- Koweït
('Koweït', 'Koweït', '🇰🇼'),
('Al Ahmadi', 'Koweït', '🇰🇼'),
('Hawalli', 'Koweït', '🇰🇼'),
('As Salimiyah', 'Koweït', '🇰🇼'),
('Sabah as Salim', 'Koweït', '🇰🇼'),
('Al Farwaniyah', 'Koweït', '🇰🇼'),
('Al Jahra', 'Koweït', '🇰🇼'),
('Fahaheel', 'Koweït', '🇰🇼'),
('Mangaf', 'Koweït', '🇰🇼'),
('Salmiya', 'Koweït', '🇰🇼'),

-- Bahreïn
('Manama', 'Bahreïn', '🇧🇭'),
('Riffa', 'Bahreïn', '🇧🇭'),
('Muharraq', 'Bahreïn', '🇧🇭'),
('Hamad Town', 'Bahreïn', '🇧🇭'),
('Isa Town', 'Bahreïn', '🇧🇭'),
('Sitra', 'Bahreïn', '🇧🇭'),
('Budaiya', 'Bahreïn', '🇧🇭'),
('Jidhafs', 'Bahreïn', '🇧🇭'),
('Al-Hidd', 'Bahreïn', '🇧🇭'),
('Sanabis', 'Bahreïn', '🇧🇭'),

-- Israël
('Tel Aviv', 'Israël', '🇮🇱'),
('Jérusalem', 'Israël', '🇮🇱'),
('Haïfa', 'Israël', '🇮🇱'),
('Rishon LeZion', 'Israël', '🇮🇱'),
('Petah Tikva', 'Israël', '🇮🇱'),
('Ashdod', 'Israël', '🇮🇱'),
('Netanya', 'Israël', '🇮🇱'),
('Beersheba', 'Israël', '🇮🇱'),
('Eilat', 'Israël', '🇮🇱'),
('Herzliya', 'Israël', '🇮🇱'),

-- Jordanie
('Amman', 'Jordanie', '🇯🇴'),
('Zarqa', 'Jordanie', '🇯🇴'),
('Irbid', 'Jordanie', '🇯🇴'),
('Petra', 'Jordanie', '🇯🇴'),
('Aqaba', 'Jordanie', '🇯🇴'),
('Madaba', 'Jordanie', '🇯🇴'),
('Jerash', 'Jordanie', '🇯🇴'),
('Ajloun', 'Jordanie', '🇯🇴'),
('Karak', 'Jordanie', '🇯🇴'),
('Salt', 'Jordanie', '🇯🇴'),

-- Liban
('Beyrouth', 'Liban', '🇱🇧'),
('Tripoli', 'Liban', '🇱🇧'),
('Sidon', 'Liban', '🇱🇧'),
('Tyr', 'Liban', '🇱🇧'),
('Jounieh', 'Liban', '🇱🇧'),
('Zahlé', 'Liban', '🇱🇧'),
('Byblos', 'Liban', '🇱🇧'),
('Baalbek', 'Liban', '🇱🇧'),
('Nabatieh', 'Liban', '🇱🇧'),
('Batroun', 'Liban', '🇱🇧'),

-- États-Unis
('New York', 'États-Unis', '🇺🇸'),
('Los Angeles', 'États-Unis', '🇺🇸'),
('Chicago', 'États-Unis', '🇺🇸'),
('Houston', 'États-Unis', '🇺🇸'),
('Phoenix', 'États-Unis', '🇺🇸'),
('Philadelphie', 'États-Unis', '🇺🇸'),
('San Antonio', 'États-Unis', '🇺🇸'),
('San Diego', 'États-Unis', '🇺🇸'),
('Dallas', 'États-Unis', '🇺🇸'),
('San José', 'États-Unis', '🇺🇸'),
('San Francisco', 'États-Unis', '🇺🇸'),
('Las Vegas', 'États-Unis', '🇺🇸'),
('Miami', 'États-Unis', '🇺🇸'),
('Boston', 'États-Unis', '🇺🇸'),
('Seattle', 'États-Unis', '🇺🇸'),
('Washington DC', 'États-Unis', '🇺🇸'),
('Nouvelle-Orléans', 'États-Unis', '🇺🇸'),
('Honolulu', 'États-Unis', '🇺🇸'),
('Orlando', 'États-Unis', '🇺🇸'),
('Atlanta', 'États-Unis', '🇺🇸'),

-- Canada
('Toronto', 'Canada', '🇨🇦'),
('Montréal', 'Canada', '🇨🇦'),
('Vancouver', 'Canada', '🇨🇦'),
('Calgary', 'Canada', '🇨🇦'),
('Edmonton', 'Canada', '🇨🇦'),
('Ottawa', 'Canada', '🇨🇦'),
('Winnipeg', 'Canada', '🇨🇦'),
('Québec', 'Canada', '🇨🇦'),
('Halifax', 'Canada', '🇨🇦'),
('Victoria', 'Canada', '🇨🇦'),

-- Mexique
('Mexico', 'Mexique', '🇲🇽'),
('Guadalajara', 'Mexique', '🇲🇽'),
('Monterrey', 'Mexique', '🇲🇽'),
('Puebla', 'Mexique', '🇲🇽'),
('Tijuana', 'Mexique', '🇲🇽'),
('Cancún', 'Mexique', '🇲🇽'),
('Playa del Carmen', 'Mexique', '🇲🇽'),
('Tulum', 'Mexique', '🇲🇽'),
('Puerto Vallarta', 'Mexique', '🇲🇽'),
('Oaxaca', 'Mexique', '🇲🇽'),

-- Brésil
('São Paulo', 'Brésil', '🇧🇷'),
('Rio de Janeiro', 'Brésil', '🇧🇷'),
('Brasília', 'Brésil', '🇧🇷'),
('Salvador', 'Brésil', '🇧🇷'),
('Fortaleza', 'Brésil', '🇧🇷'),
('Belo Horizonte', 'Brésil', '🇧🇷'),
('Manaus', 'Brésil', '🇧🇷'),
('Recife', 'Brésil', '🇧🇷'),
('Porto Alegre', 'Brésil', '🇧🇷'),
('Curitiba', 'Brésil', '🇧🇷'),

-- Argentine
('Buenos Aires', 'Argentine', '🇦🇷'),
('Córdoba', 'Argentine', '🇦🇷'),
('Rosario', 'Argentine', '🇦🇷'),
('Mendoza', 'Argentine', '🇦🇷'),
('Ushuaia', 'Argentine', '🇦🇷'),
('San Miguel de Tucumán', 'Argentine', '🇦🇷'),
('Mar del Plata', 'Argentine', '🇦🇷'),
('Salta', 'Argentine', '🇦🇷'),
('Bariloche', 'Argentine', '🇦🇷'),
('El Calafate', 'Argentine', '🇦🇷'),

-- Pérou
('Lima', 'Pérou', '🇵🇪'),
('Arequipa', 'Pérou', '🇵🇪'),
('Trujillo', 'Pérou', '🇵🇪'),
('Cusco', 'Pérou', '🇵🇪'),
('Machu Picchu', 'Pérou', '🇵🇪'),
('Chiclayo', 'Pérou', '🇵🇪'),
('Piura', 'Pérou', '🇵🇪'),
('Iquitos', 'Pérou', '🇵🇪'),
('Huancayo', 'Pérou', '🇵🇪'),
('Puno', 'Pérou', '🇵🇪'),

-- Colombie
('Bogotá', 'Colombie', '🇨🇴'),
('Medellín', 'Colombie', '🇨🇴'),
('Cali', 'Colombie', '🇨🇴'),
('Barranquilla', 'Colombie', '🇨🇴'),
('Carthagène', 'Colombie', '🇨🇴'),
('Cucuta', 'Colombie', '🇨🇴'),
('Santa Marta', 'Colombie', '🇨🇴'),
('Manizales', 'Colombie', '🇨🇴'),
('Pereira', 'Colombie', '🇨🇴'),
('San Andrés', 'Colombie', '🇨🇴'),

-- Chili
('Santiago', 'Chili', '🇨🇱'),
('Valparaíso', 'Chili', '🇨🇱'),
('Concepción', 'Chili', '🇨🇱'),
('La Serena', 'Chili', '🇨🇱'),
('Antofagasta', 'Chili', '🇨🇱'),
('Temuco', 'Chili', '🇨🇱'),
('Viña del Mar', 'Chili', '🇨🇱'),
('Iquique', 'Chili', '🇨🇱'),
('Puerto Montt', 'Chili', '🇨🇱'),
('Punta Arenas', 'Chili', '🇨🇱'),

-- Équateur
('Quito', 'Équateur', '🇪🇨'),
('Guayaquil', 'Équateur', '🇪🇨'),
('Cuenca', 'Équateur', '🇪🇨'),
('Galápagos', 'Équateur', '🇪🇨'),
('Manta', 'Équateur', '🇪🇨'),
('Machala', 'Équateur', '🇪🇨'),
('Loja', 'Équateur', '🇪🇨'),
('Ambato', 'Équateur', '🇪🇨'),
('Riobamba', 'Équateur', '🇪🇨'),
('Baños', 'Équateur', '🇪🇨'),

-- Bolivie
('La Paz', 'Bolivie', '🇧🇴'),
('Santa Cruz', 'Bolivie', '🇧🇴'),
('Cochabamba', 'Bolivie', '🇧🇴'),
('Sucre', 'Bolivie', '🇧🇴'),
('Potosí', 'Bolivie', '🇧🇴'),
('Oruro', 'Bolivie', '🇧🇴'),
('Tarija', 'Bolivie', '🇧🇴'),
('Uyuni', 'Bolivie', '🇧🇴'),
('Copacabana', 'Bolivie', '🇧🇴'),
('Trinidad', 'Bolivie', '🇧🇴'),

-- Venezuela
('Caracas', 'Venezuela', '🇻🇪'),
('Maracaibo', 'Venezuela', '🇻🇪'),
('Valencia', 'Venezuela', '🇻🇪'),
('Barquisimeto', 'Venezuela', '🇻🇪'),
('Ciudad Guayana', 'Venezuela', '🇻🇪'),
('Maturín', 'Venezuela', '🇻🇪'),
('Barcelona', 'Venezuela', '🇻🇪'),
('Isla Margarita', 'Venezuela', '🇻🇪'),
('Mérida', 'Venezuela', '🇻🇪'),
('Los Roques', 'Venezuela', '🇻🇪'),

-- Paraguay
('Asunción', 'Paraguay', '🇵🇾'),
('Ciudad del Este', 'Paraguay', '🇵🇾'),
('San Lorenzo', 'Paraguay', '🇵🇾'),
('Luque', 'Paraguay', '🇵🇾'),
('Capiatá', 'Paraguay', '🇵🇾'),
('Encarnación', 'Paraguay', '🇵🇾'),
('Pedro Juan Caballero', 'Paraguay', '🇵🇾'),
('Concepción', 'Paraguay', '🇵🇾'),
('Coronel Oviedo', 'Paraguay', '🇵🇾'),
('Villarrica', 'Paraguay', '🇵🇾'),

-- Uruguay
('Montevideo', 'Uruguay', '🇺🇾'),
('Salto', 'Uruguay', '🇺🇾'),
('Paysandú', 'Uruguay', '🇺🇾'),
('Maldonado', 'Uruguay', '🇺🇾'),
('Rivera', 'Uruguay', '🇺🇾'),
('Punta del Este', 'Uruguay', '🇺🇾'),
('Colonia del Sacramento', 'Uruguay', '🇺🇾'),
('Mercedes', 'Uruguay', '🇺🇾'),
('Melo', 'Uruguay', '🇺🇾'),
('Tacuarembó', 'Uruguay', '🇺🇾'),

-- Australie
('Sydney', 'Australie', '🇦🇺'),
('Melbourne', 'Australie', '🇦🇺'),
('Brisbane', 'Australie', '🇦🇺'),
('Perth', 'Australie', '🇦🇺'),
('Adelaide', 'Australie', '🇦🇺'),
('Gold Coast', 'Australie', '🇦🇺'),
('Canberra', 'Australie', '🇦🇺'),
('Hobart', 'Australie', '🇦🇺'),
('Darwin', 'Australie', '🇦🇺'),
('Cairns', 'Australie', '🇦🇺'),

-- Nouvelle-Zélande
('Auckland', 'Nouvelle-Zélande', '🇳🇿'),
('Wellington', 'Nouvelle-Zélande', '🇳🇿'),
('Christchurch', 'Nouvelle-Zélande', '🇳🇿'),
('Hamilton', 'Nouvelle-Zélande', '🇳🇿'),
('Queenstown', 'Nouvelle-Zélande', '🇳🇿'),
('Tauranga', 'Nouvelle-Zélande', '🇳🇿'),
('Dunedin', 'Nouvelle-Zélande', '🇳🇿'),
('Rotorua', 'Nouvelle-Zélande', '🇳🇿'),
('Napier', 'Nouvelle-Zélande', '🇳🇿'),
('Nelson', 'Nouvelle-Zélande', '🇳🇿')
) AS v(name, country, country_code)
WHERE NOT EXISTS (
  SELECT 1 FROM cities WHERE cities.name = v.name AND cities.country = v.country
);