-- Insert comprehensive European cities and remaining world cities
INSERT INTO cities (name, country, country_code)
SELECT * FROM (VALUES
-- France (villes complémentaires)
('Paris', 'France', '🇫🇷'),
('Marseille', 'France', '🇫🇷'),
('Lyon', 'France', '🇫🇷'),
('Toulouse', 'France', '🇫🇷'),
('Nice', 'France', '🇫🇷'),
('Nantes', 'France', '🇫🇷'),
('Strasbourg', 'France', '🇫🇷'),
('Montpellier', 'France', '🇫🇷'),
('Bordeaux', 'France', '🇫🇷'),
('Lille', 'France', '🇫🇷'),
('Rennes', 'France', '🇫🇷'),
('Reims', 'France', '🇫🇷'),
('Saint-Étienne', 'France', '🇫🇷'),
('Le Havre', 'France', '🇫🇷'),
('Toulon', 'France', '🇫🇷'),
('Grenoble', 'France', '🇫🇷'),
('Dijon', 'France', '🇫🇷'),
('Angers', 'France', '🇫🇷'),
('Nîmes', 'France', '🇫🇷'),
('Villeurbanne', 'France', '🇫🇷'),

-- Italie
('Rome', 'Italie', '🇮🇹'),
('Milan', 'Italie', '🇮🇹'),
('Naples', 'Italie', '🇮🇹'),
('Turin', 'Italie', '🇮🇹'),
('Palerme', 'Italie', '🇮🇹'),
('Gênes', 'Italie', '🇮🇹'),
('Bologne', 'Italie', '🇮🇹'),
('Florence', 'Italie', '🇮🇹'),
('Venise', 'Italie', '🇮🇹'),
('Vérone', 'Italie', '🇮🇹'),
('Catane', 'Italie', '🇮🇹'),
('Bari', 'Italie', '🇮🇹'),
('Messine', 'Italie', '🇮🇹'),
('Padoue', 'Italie', '🇮🇹'),
('Trieste', 'Italie', '🇮🇹'),

-- Espagne
('Madrid', 'Espagne', '🇪🇸'),
('Barcelone', 'Espagne', '🇪🇸'),
('Valence', 'Espagne', '🇪🇸'),
('Séville', 'Espagne', '🇪🇸'),
('Saragosse', 'Espagne', '🇪🇸'),
('Malaga', 'Espagne', '🇪🇸'),
('Murcie', 'Espagne', '🇪🇸'),
('Palma de Majorque', 'Espagne', '🇪🇸'),
('Bilbao', 'Espagne', '🇪🇸'),
('Grenade', 'Espagne', '🇪🇸'),
('Alicante', 'Espagne', '🇪🇸'),
('Cordoue', 'Espagne', '🇪🇸'),
('Tolède', 'Espagne', '🇪🇸'),
('Saint-Sébastien', 'Espagne', '🇪🇸'),
('Ibiza', 'Espagne', '🇪🇸'),

-- Portugal
('Lisbonne', 'Portugal', '🇵🇹'),
('Porto', 'Portugal', '🇵🇹'),
('Braga', 'Portugal', '🇵🇹'),
('Coimbra', 'Portugal', '🇵🇹'),
('Faro', 'Portugal', '🇵🇹'),
('Funchal', 'Portugal', '🇵🇹'),
('Aveiro', 'Portugal', '🇵🇹'),
('Évora', 'Portugal', '🇵🇹'),
('Albufeira', 'Portugal', '🇵🇹'),
('Lagos', 'Portugal', '🇵🇹'),

-- Royaume-Uni
('Londres', 'Royaume-Uni', '🇬🇧'),
('Manchester', 'Royaume-Uni', '🇬🇧'),
('Birmingham', 'Royaume-Uni', '🇬🇧'),
('Liverpool', 'Royaume-Uni', '🇬🇧'),
('Leeds', 'Royaume-Uni', '🇬🇧'),
('Newcastle', 'Royaume-Uni', '🇬🇧'),
('Sheffield', 'Royaume-Uni', '🇬🇧'),
('Bristol', 'Royaume-Uni', '🇬🇧'),
('Édimbourg', 'Royaume-Uni', '🇬🇧'),
('Glasgow', 'Royaume-Uni', '🇬🇧'),
('Cardiff', 'Royaume-Uni', '🇬🇧'),
('Belfast', 'Royaume-Uni', '🇬🇧'),
('Brighton', 'Royaume-Uni', '🇬🇧'),
('Oxford', 'Royaume-Uni', '🇬🇧'),
('Cambridge', 'Royaume-Uni', '🇬🇧'),

-- Allemagne
('Berlin', 'Allemagne', '🇩🇪'),
('Hambourg', 'Allemagne', '🇩🇪'),
('Munich', 'Allemagne', '🇩🇪'),
('Cologne', 'Allemagne', '🇩🇪'),
('Francfort', 'Allemagne', '🇩🇪'),
('Stuttgart', 'Allemagne', '🇩🇪'),
('Düsseldorf', 'Allemagne', '🇩🇪'),
('Dortmund', 'Allemagne', '🇩🇪'),
('Essen', 'Allemagne', '🇩🇪'),
('Leipzig', 'Allemagne', '🇩🇪'),
('Dresde', 'Allemagne', '🇩🇪'),
('Hanovre', 'Allemagne', '🇩🇪'),
('Nuremberg', 'Allemagne', '🇩🇪'),
('Brême', 'Allemagne', '🇩🇪'),
('Heidelberg', 'Allemagne', '🇩🇪'),

-- Pays-Bas
('Amsterdam', 'Pays-Bas', '🇳🇱'),
('Rotterdam', 'Pays-Bas', '🇳🇱'),
('La Haye', 'Pays-Bas', '🇳🇱'),
('Utrecht', 'Pays-Bas', '🇳🇱'),
('Eindhoven', 'Pays-Bas', '🇳🇱'),
('Groningue', 'Pays-Bas', '🇳🇱'),
('Maastricht', 'Pays-Bas', '🇳🇱'),
('Delft', 'Pays-Bas', '🇳🇱'),
('Leiden', 'Pays-Bas', '🇳🇱'),
('Haarlem', 'Pays-Bas', '🇳🇱'),

-- Belgique
('Bruxelles', 'Belgique', '🇧🇪'),
('Anvers', 'Belgique', '🇧🇪'),
('Gand', 'Belgique', '🇧🇪'),
('Charleroi', 'Belgique', '🇧🇪'),
('Liège', 'Belgique', '🇧🇪'),
('Bruges', 'Belgique', '🇧🇪'),
('Namur', 'Belgique', '🇧🇪'),
('Louvain', 'Belgique', '🇧🇪'),
('Mons', 'Belgique', '🇧🇪'),
('Dinant', 'Belgique', '🇧🇪'),

-- Suisse
('Zurich', 'Suisse', '🇨🇭'),
('Genève', 'Suisse', '🇨🇭'),
('Bâle', 'Suisse', '🇨🇭'),
('Lausanne', 'Suisse', '🇨🇭'),
('Berne', 'Suisse', '🇨🇭'),
('Lucerne', 'Suisse', '🇨🇭'),
('Lugano', 'Suisse', '🇨🇭'),
('Interlaken', 'Suisse', '🇨🇭'),
('Zermatt', 'Suisse', '🇨🇭'),
('Montreux', 'Suisse', '🇨🇭'),

-- Autriche
('Vienne', 'Autriche', '🇦🇹'),
('Graz', 'Autriche', '🇦🇹'),
('Linz', 'Autriche', '🇦🇹'),
('Salzbourg', 'Autriche', '🇦🇹'),
('Innsbruck', 'Autriche', '🇦🇹'),
('Klagenfurt', 'Autriche', '🇦🇹'),
('Hallstatt', 'Autriche', '🇦🇹'),
('Bad Gastein', 'Autriche', '🇦🇹'),
('St. Anton', 'Autriche', '🇦🇹'),
('Wachau', 'Autriche', '🇦🇹'),

-- Pologne
('Varsovie', 'Pologne', '🇵🇱'),
('Cracovie', 'Pologne', '🇵🇱'),
('Łódź', 'Pologne', '🇵🇱'),
('Wrocław', 'Pologne', '🇵🇱'),
('Poznań', 'Pologne', '🇵🇱'),
('Gdańsk', 'Pologne', '🇵🇱'),
('Sopot', 'Pologne', '🇵🇱'),
('Zakopane', 'Pologne', '🇵🇱'),
('Toruń', 'Pologne', '🇵🇱'),
('Gdynia', 'Pologne', '🇵🇱'),

-- Tchéquie
('Prague', 'Tchéquie', '🇨🇿'),
('Brno', 'Tchéquie', '🇨🇿'),
('Ostrava', 'Tchéquie', '🇨🇿'),
('Plzeň', 'Tchéquie', '🇨🇿'),
('Liberec', 'Tchéquie', '🇨🇿'),
('Olomouc', 'Tchéquie', '🇨🇿'),
('České Budějovice', 'Tchéquie', '🇨🇿'),
('Karlovy Vary', 'Tchéquie', '🇨🇿'),
('Český Krumlov', 'Tchéquie', '🇨🇿'),
('Kutná Hora', 'Tchéquie', '🇨🇿'),

-- Hongrie
('Budapest', 'Hongrie', '🇭🇺'),
('Debrecen', 'Hongrie', '🇭🇺'),
('Szeged', 'Hongrie', '🇭🇺'),
('Miskolc', 'Hongrie', '🇭🇺'),
('Pécs', 'Hongrie', '🇭🇺'),
('Győr', 'Hongrie', '🇭🇺'),
('Eger', 'Hongrie', '🇭🇺'),
('Kecskemét', 'Hongrie', '🇭🇺'),
('Székesfehérvár', 'Hongrie', '🇭🇺'),
('Sopron', 'Hongrie', '🇭🇺'),

-- Grèce
('Athènes', 'Grèce', '🇬🇷'),
('Thessalonique', 'Grèce', '🇬🇷'),
('Patras', 'Grèce', '🇬🇷'),
('Santorin', 'Grèce', '🇬🇷'),
('Mykonos', 'Grèce', '🇬🇷'),
('Rhodes', 'Grèce', '🇬🇷'),
('Corfou', 'Grèce', '🇬🇷'),
('Crète', 'Grèce', '🇬🇷'),
('Héraklion', 'Grèce', '🇬🇷'),
('Naxos', 'Grèce', '🇬🇷'),

-- Turquie
('Istanbul', 'Turquie', '🇹🇷'),
('Ankara', 'Turquie', '🇹🇷'),
('Izmir', 'Turquie', '🇹🇷'),
('Bursa', 'Turquie', '🇹🇷'),
('Antalya', 'Turquie', '🇹🇷'),
('Cappadoce', 'Turquie', '🇹🇷'),
('Bodrum', 'Turquie', '🇹🇷'),
('Marmaris', 'Turquie', '🇹🇷'),
('Fethiye', 'Turquie', '🇹🇷'),
('Pamukkale', 'Turquie', '🇹🇷'),

-- Croatie
('Zagreb', 'Croatie', '🇭🇷'),
('Split', 'Croatie', '🇭🇷'),
('Dubrovnik', 'Croatie', '🇭🇷'),
('Rijeka', 'Croatie', '🇭🇷'),
('Zadar', 'Croatie', '🇭🇷'),
('Pula', 'Croatie', '🇭🇷'),
('Hvar', 'Croatie', '🇭🇷'),
('Rovinj', 'Croatie', '🇭🇷'),
('Korčula', 'Croatie', '🇭🇷'),
('Poreč', 'Croatie', '🇭🇷'),

-- Serbie
('Belgrade', 'Serbie', '🇷🇸'),
('Novi Sad', 'Serbie', '🇷🇸'),
('Niš', 'Serbie', '🇷🇸'),
('Kragujevac', 'Serbie', '🇷🇸'),
('Subotica', 'Serbie', '🇷🇸'),
('Novi Pazar', 'Serbie', '🇷🇸'),
('Kraljevo', 'Serbie', '🇷🇸'),
('Smederevo', 'Serbie', '🇷🇸'),
('Leskovac', 'Serbie', '🇷🇸'),
('Užice', 'Serbie', '🇷🇸'),

-- Roumanie
('Bucarest', 'Roumanie', '🇷🇴'),
('Cluj-Napoca', 'Roumanie', '🇷🇴'),
('Timișoara', 'Roumanie', '🇷🇴'),
('Iași', 'Roumanie', '🇷🇴'),
('Constanța', 'Roumanie', '🇷🇴'),
('Craiova', 'Roumanie', '🇷🇴'),
('Brașov', 'Roumanie', '🇷🇴'),
('Sibiu', 'Roumanie', '🇷🇴'),
('Sighișoara', 'Roumanie', '🇷🇴'),
('Oradea', 'Roumanie', '🇷🇴'),

-- Bulgarie
('Sofia', 'Bulgarie', '🇧🇬'),
('Plovdiv', 'Bulgarie', '🇧🇬'),
('Varna', 'Bulgarie', '🇧🇬'),
('Burgas', 'Bulgarie', '🇧🇬'),
('Ruse', 'Bulgarie', '🇧🇬'),
('Stara Zagora', 'Bulgarie', '🇧🇬'),
('Pleven', 'Bulgarie', '🇧🇬'),
('Veliko Tarnovo', 'Bulgarie', '🇧🇬'),
('Bansko', 'Bulgarie', '🇧🇬'),
('Nessebar', 'Bulgarie', '🇧🇬'),

-- Russie
('Moscou', 'Russie', '🇷🇺'),
('Saint-Pétersbourg', 'Russie', '🇷🇺'),
('Kazan', 'Russie', '🇷🇺'),
('Sotchi', 'Russie', '🇷🇺'),
('Ekaterinbourg', 'Russie', '🇷🇺'),
('Novgorod', 'Russie', '🇷🇺'),
('Vladivostok', 'Russie', '🇷🇺'),
('Kaliningrad', 'Russie', '🇷🇺'),
('Irkoutsk', 'Russie', '🇷🇺'),
('Krasnodar', 'Russie', '🇷🇺'),

-- Ukraine
('Kiev', 'Ukraine', '🇺🇦'),
('Kharkiv', 'Ukraine', '🇺🇦'),
('Odessa', 'Ukraine', '🇺🇦'),
('Dnipro', 'Ukraine', '🇺🇦'),
('Lviv', 'Ukraine', '🇺🇦'),
('Zaporijjia', 'Ukraine', '🇺🇦'),
('Kryvyï Rih', 'Ukraine', '🇺🇦'),
('Mykolaïv', 'Ukraine', '🇺🇦'),
('Vinnytsia', 'Ukraine', '🇺🇦'),
('Tchernivtsi', 'Ukraine', '🇺🇦'),

-- Pays nordiques - Norvège
('Oslo', 'Norvège', '🇳🇴'),
('Bergen', 'Norvège', '🇳🇴'),
('Trondheim', 'Norvège', '🇳🇴'),
('Stavanger', 'Norvège', '🇳🇴'),
('Tromsø', 'Norvège', '🇳🇴'),
('Ålesund', 'Norvège', '🇳🇴'),
('Kristiansand', 'Norvège', '🇳🇴'),
('Bodø', 'Norvège', '🇳🇴'),
('Drammen', 'Norvège', '🇳🇴'),
('Longyearbyen', 'Norvège', '🇳🇴'),

-- Suède
('Stockholm', 'Suède', '🇸🇪'),
('Göteborg', 'Suède', '🇸🇪'),
('Malmö', 'Suède', '🇸🇪'),
('Uppsala', 'Suède', '🇸🇪'),
('Västerås', 'Suède', '🇸🇪'),
('Örebro', 'Suède', '🇸🇪'),
('Linköping', 'Suède', '🇸🇪'),
('Helsingborg', 'Suède', '🇸🇪'),
('Jönköping', 'Suède', '🇸🇪'),
('Kiruna', 'Suède', '🇸🇪'),

-- Finlande
('Helsinki', 'Finlande', '🇫🇮'),
('Espoo', 'Finlande', '🇫🇮'),
('Tampere', 'Finlande', '🇫🇮'),
('Vantaa', 'Finlande', '🇫🇮'),
('Oulu', 'Finlande', '🇫🇮'),
('Turku', 'Finlande', '🇫🇮'),
('Jyväskylä', 'Finlande', '🇫🇮'),
('Lahti', 'Finlande', '🇫🇮'),
('Kuopio', 'Finlande', '🇫🇮'),
('Rovaniemi', 'Finlande', '🇫🇮'),

-- Danemark
('Copenhague', 'Danemark', '🇩🇰'),
('Aarhus', 'Danemark', '🇩🇰'),
('Odense', 'Danemark', '🇩🇰'),
('Aalborg', 'Danemark', '🇩🇰'),
('Esbjerg', 'Danemark', '🇩🇰'),
('Randers', 'Danemark', '🇩🇰'),
('Kolding', 'Danemark', '🇩🇰'),
('Horsens', 'Danemark', '🇩🇰'),
('Vejle', 'Danemark', '🇩🇰'),
('Roskilde', 'Danemark', '🇩🇰'),

-- Islande
('Reykjavik', 'Islande', '🇮🇸'),
('Akureyri', 'Islande', '🇮🇸'),
('Hafnarfjörður', 'Islande', '🇮🇸'),
('Kópavogur', 'Islande', '🇮🇸'),
('Reykjanesbær', 'Islande', '🇮🇸'),
('Selfoss', 'Islande', '🇮🇸'),
('Vik', 'Islande', '🇮🇸'),
('Höfn', 'Islande', '🇮🇸'),
('Egilsstaðir', 'Islande', '🇮🇸'),
('Húsavík', 'Islande', '🇮🇸'),

-- Irlande
('Dublin', 'Irlande', '🇮🇪'),
('Cork', 'Irlande', '🇮🇪'),
('Galway', 'Irlande', '🇮🇪'),
('Limerick', 'Irlande', '🇮🇪'),
('Waterford', 'Irlande', '🇮🇪'),
('Killarney', 'Irlande', '🇮🇪'),
('Dingle', 'Irlande', '🇮🇪'),
('Kilkenny', 'Irlande', '🇮🇪'),
('Sligo', 'Irlande', '🇮🇪'),
('Doolin', 'Irlande', '🇮🇪'),

-- Pays baltes - Estonie
('Tallinn', 'Estonie', '🇪🇪'),
('Tartu', 'Estonie', '🇪🇪'),
('Narva', 'Estonie', '🇪🇪'),
('Pärnu', 'Estonie', '🇪🇪'),
('Kuressaare', 'Estonie', '🇪🇪'),
('Haapsalu', 'Estonie', '🇪🇪'),
('Rakvere', 'Estonie', '🇪🇪'),
('Viljandi', 'Estonie', '🇪🇪'),
('Jõhvi', 'Estonie', '🇪🇪'),
('Võru', 'Estonie', '🇪🇪'),

-- Lettonie
('Riga', 'Lettonie', '🇱🇻'),
('Daugavpils', 'Lettonie', '🇱🇻'),
('Liepāja', 'Lettonie', '🇱🇻'),
('Jelgava', 'Lettonie', '🇱🇻'),
('Jūrmala', 'Lettonie', '🇱🇻'),
('Ventspils', 'Lettonie', '🇱🇻'),
('Rēzekne', 'Lettonie', '🇱🇻'),
('Valmiera', 'Lettonie', '🇱🇻'),
('Jēkabpils', 'Lettonie', '🇱🇻'),
('Ogre', 'Lettonie', '🇱🇻'),

-- Lituanie
('Vilnius', 'Lituanie', '🇱🇹'),
('Kaunas', 'Lituanie', '🇱🇹'),
('Klaipėda', 'Lituanie', '🇱🇹'),
('Šiauliai', 'Lituanie', '🇱🇹'),
('Panevėžys', 'Lituanie', '🇱🇹'),
('Alytus', 'Lituanie', '🇱🇹'),
('Marijampolė', 'Lituanie', '🇱🇹'),
('Mažeikiai', 'Lituanie', '🇱🇹'),
('Jonava', 'Lituanie', '🇱🇹'),
('Utena', 'Lituanie', '🇱🇹'),

-- Slovénie
('Ljubljana', 'Slovénie', '🇸🇮'),
('Maribor', 'Slovénie', '🇸🇮'),
('Celje', 'Slovénie', '🇸🇮'),
('Kranj', 'Slovénie', '🇸🇮'),
('Bled', 'Slovénie', '🇸🇮'),
('Koper', 'Slovénie', '🇸🇮'),
('Novo Mesto', 'Slovénie', '🇸🇮'),
('Ptuj', 'Slovénie', '🇸🇮'),
('Piran', 'Slovénie', '🇸🇮'),
('Portorož', 'Slovénie', '🇸🇮'),

-- Slovaquie
('Bratislava', 'Slovaquie', '🇸🇰'),
('Košice', 'Slovaquie', '🇸🇰'),
('Prešov', 'Slovaquie', '🇸🇰'),
('Žilina', 'Slovaquie', '🇸🇰'),
('Banská Bystrica', 'Slovaquie', '🇸🇰'),
('Nitra', 'Slovaquie', '🇸🇰'),
('Trenčín', 'Slovaquie', '🇸🇰'),
('Martin', 'Slovaquie', '🇸🇰'),
('Poprad', 'Slovaquie', '🇸🇰'),
('Trnava', 'Slovaquie', '🇸🇰'),

-- Albanie
('Tirana', 'Albanie', '🇦🇱'),
('Durrës', 'Albanie', '🇦🇱'),
('Vlorë', 'Albanie', '🇦🇱'),
('Shkodër', 'Albanie', '🇦🇱'),
('Berat', 'Albanie', '🇦🇱'),
('Gjirokastër', 'Albanie', '🇦🇱'),
('Sarandë', 'Albanie', '🇦🇱'),
('Korçë', 'Albanie', '🇦🇱'),
('Kukës', 'Albanie', '🇦🇱'),
('Fier', 'Albanie', '🇦🇱'),

-- Bosnie-Herzégovine
('Sarajevo', 'Bosnie-Herzégovine', '🇧🇦'),
('Banja Luka', 'Bosnie-Herzégovine', '🇧🇦'),
('Tuzla', 'Bosnie-Herzégovine', '🇧🇦'),
('Zenica', 'Bosnie-Herzégovine', '🇧🇦'),
('Mostar', 'Bosnie-Herzégovine', '🇧🇦'),
('Bihać', 'Bosnie-Herzégovine', '🇧🇦'),
('Bijeljina', 'Bosnie-Herzégovine', '🇧🇦'),
('Prijedor', 'Bosnie-Herzégovine', '🇧🇦'),
('Trebinje', 'Bosnie-Herzégovine', '🇧🇦'),
('Brčko', 'Bosnie-Herzégovine', '🇧🇦'),

-- Macédoine du Nord
('Skopje', 'Macédoine du Nord', '🇲🇰'),
('Bitola', 'Macédoine du Nord', '🇲🇰'),
('Kumanovo', 'Macédoine du Nord', '🇲🇰'),
('Prilep', 'Macédoine du Nord', '🇲🇰'),
('Tetovo', 'Macédoine du Nord', '🇲🇰'),
('Ohrid', 'Macédoine du Nord', '🇲🇰'),
('Veles', 'Macédoine du Nord', '🇲🇰'),
('Štip', 'Macédoine du Nord', '🇲🇰'),
('Gostivar', 'Macédoine du Nord', '🇲🇰'),
('Strumica', 'Macédoine du Nord', '🇲🇰'),

-- Monténégro
('Podgorica', 'Monténégro', '🇲🇪'),
('Kotor', 'Monténégro', '🇲🇪'),
('Budva', 'Monténégro', '🇲🇪'),
('Nikšić', 'Monténégro', '🇲🇪'),
('Herceg Novi', 'Monténégro', '🇲🇪'),
('Pljevlja', 'Monténégro', '🇲🇪'),
('Bijelo Polje', 'Monténégro', '🇲🇪'),
('Bar', 'Monténégro', '🇲🇪'),
('Ulcinj', 'Monténégro', '🇲🇪'),
('Tivat', 'Monténégro', '🇲🇪'),

-- Kosovo
('Pristina', 'Kosovo', '🇽🇰'),
('Prizren', 'Kosovo', '🇽🇰'),
('Peć', 'Kosovo', '🇽🇰'),
('Mitrovica', 'Kosovo', '🇽🇰'),
('Gjakova', 'Kosovo', '🇽🇰'),
('Gjilan', 'Kosovo', '🇽🇰'),
('Ferizaj', 'Kosovo', '🇽🇰'),
('Podujevo', 'Kosovo', '🇽🇰'),
('Vushtrri', 'Kosovo', '🇽🇰'),
('Suva Reka', 'Kosovo', '🇽🇰'),

-- Caraïbes - Cuba
('La Havane', 'Cuba', '🇨🇺'),
('Santiago de Cuba', 'Cuba', '🇨🇺'),
('Varadero', 'Cuba', '🇨🇺'),
('Trinidad', 'Cuba', '🇨🇺'),
('Cienfuegos', 'Cuba', '🇨🇺'),
('Santa Clara', 'Cuba', '🇨🇺'),
('Viñales', 'Cuba', '🇨🇺'),
('Baracoa', 'Cuba', '🇨🇺'),
('Cayo Coco', 'Cuba', '🇨🇺'),
('Cayo Largo', 'Cuba', '🇨🇺'),

-- République Dominicaine
('Saint-Domingue', 'République Dominicaine', '🇩🇴'),
('Santiago', 'République Dominicaine', '🇩🇴'),
('Punta Cana', 'République Dominicaine', '🇩🇴'),
('La Romana', 'République Dominicaine', '🇩🇴'),
('Puerto Plata', 'République Dominicaine', '🇩🇴'),
('San Pedro de Macorís', 'République Dominicaine', '🇩🇴'),
('Samaná', 'République Dominicaine', '🇩🇴'),
('Bávaro', 'République Dominicaine', '🇩🇴'),
('Cabarete', 'République Dominicaine', '🇩🇴'),
('Las Terrenas', 'République Dominicaine', '🇩🇴'),

-- Jamaïque
('Kingston', 'Jamaïque', '🇯🇲'),
('Montego Bay', 'Jamaïque', '🇯🇲'),
('Ocho Rios', 'Jamaïque', '🇯🇲'),
('Negril', 'Jamaïque', '🇯🇲'),
('Port Antonio', 'Jamaïque', '🇯🇲'),
('Mandeville', 'Jamaïque', '🇯🇲'),
('Spanish Town', 'Jamaïque', '🇯🇲'),
('May Pen', 'Jamaïque', '🇯🇲'),
('Portmore', 'Jamaïque', '🇯🇲'),
('Runaway Bay', 'Jamaïque', '🇯🇲'),

-- Costa Rica
('San José', 'Costa Rica', '🇨🇷'),
('Alajuela', 'Costa Rica', '🇨🇷'),
('Manuel Antonio', 'Costa Rica', '🇨🇷'),
('Puerto Viejo', 'Costa Rica', '🇨🇷'),
('Monteverde', 'Costa Rica', '🇨🇷'),
('Tamarindo', 'Costa Rica', '🇨🇷'),
('Jacó', 'Costa Rica', '🇨🇷'),
('La Fortuna', 'Costa Rica', '🇨🇷'),
('Puerto Limón', 'Costa Rica', '🇨🇷'),
('Puntarenas', 'Costa Rica', '🇨🇷'),

-- Panama
('Panama City', 'Panama', '🇵🇦'),
('Colón', 'Panama', '🇵🇦'),
('Bocas del Toro', 'Panama', '🇵🇦'),
('Boquete', 'Panama', '🇵🇦'),
('David', 'Panama', '🇵🇦'),
('Santiago', 'Panama', '🇵🇦'),
('Chitré', 'Panama', '🇵🇦'),
('San Miguelito', 'Panama', '🇵🇦'),
('Las Tablas', 'Panama', '🇵🇦'),
('Penonomé', 'Panama', '🇵🇦'),

-- Polynésie & Pacifique
('Papeete', 'Polynésie française', '🇵🇫'),
('Bora Bora', 'Polynésie française', '🇵🇫'),
('Moorea', 'Polynésie française', '🇵🇫'),
('Tahaa', 'Polynésie française', '🇵🇫'),
('Raiatea', 'Polynésie française', '🇵🇫'),
('Huahine', 'Polynésie française', '🇵🇫'),
('Rangiroa', 'Polynésie française', '🇵🇫'),
('Fakarava', 'Polynésie française', '🇵🇫'),
('Hiva Oa', 'Polynésie française', '🇵🇫'),
('Tikehau', 'Polynésie française', '🇵🇫'),

-- Nouvelle-Calédonie
('Nouméa', 'Nouvelle-Calédonie', '🇳🇨'),
('Dumbéa', 'Nouvelle-Calédonie', '🇳🇨'),
('Mont-Dore', 'Nouvelle-Calédonie', '🇳🇨'),
('Païta', 'Nouvelle-Calédonie', '🇳🇨'),
('Bourail', 'Nouvelle-Calédonie', '🇳🇨'),
('Koné', 'Nouvelle-Calédonie', '🇳🇨'),
('Lifou', 'Nouvelle-Calédonie', '🇳🇨'),
('Maré', 'Nouvelle-Calédonie', '🇳🇨'),
('Ouvéa', 'Nouvelle-Calédonie', '🇳🇨'),
('Île des Pins', 'Nouvelle-Calédonie', '🇳🇨'),

-- Fidji
('Suva', 'Fidji', '🇫🇯'),
('Nadi', 'Fidji', '🇫🇯'),
('Lautoka', 'Fidji', '🇫🇯'),
('Labasa', 'Fidji', '🇫🇯'),
('Sigatoka', 'Fidji', '🇫🇯'),
('Savusavu', 'Fidji', '🇫🇯'),
('Levuka', 'Fidji', '🇫🇯'),
('Ba', 'Fidji', '🇫🇯'),
('Tavua', 'Fidji', '🇫🇯'),
('Korovou', 'Fidji', '🇫🇯')
) AS v(name, country, country_code)
WHERE NOT EXISTS (
  SELECT 1 FROM cities WHERE cities.name = v.name AND cities.country = v.country
);