-- Continue adding African cities - West Africa
INSERT INTO cities (name, country, country_code) VALUES
-- Bénin
('Cotonou', 'Bénin', '🇧🇯'),
('Porto-Novo', 'Bénin', '🇧🇯'),
('Parakou', 'Bénin', '🇧🇯'),
('Djougou', 'Bénin', '🇧🇯'),
('Bohicon', 'Bénin', '🇧🇯'),
('Kandi', 'Bénin', '🇧🇯'),
('Abomey', 'Bénin', '🇧🇯'),
('Natitingou', 'Bénin', '🇧🇯'),
('Lokossa', 'Bénin', '🇧🇯'),
('Ouidah', 'Bénin', '🇧🇯'),

-- Togo
('Lomé', 'Togo', '🇹🇬'),
('Sokodé', 'Togo', '🇹🇬'),
('Kara', 'Togo', '🇹🇬'),
('Atakpamé', 'Togo', '🇹🇬'),
('Palimé', 'Togo', '🇹🇬'),
('Bassar', 'Togo', '🇹🇬'),
('Tsévié', 'Togo', '🇹🇬'),
('Aného', 'Togo', '🇹🇬'),
('Mango', 'Togo', '🇹🇬'),
('Dapaong', 'Togo', '🇹🇬'),

-- Guinée
('Conakry', 'Guinée', '🇬🇳'),
('Nzérékoré', 'Guinée', '🇬🇳'),
('Kankan', 'Guinée', '🇬🇳'),
('Kindia', 'Guinée', '🇬🇳'),
('Labé', 'Guinée', '🇬🇳'),
('Kissidougou', 'Guinée', '🇬🇳'),
('Mamou', 'Guinée', '🇬🇳'),
('Siguiri', 'Guinée', '🇬🇳'),
('Boké', 'Guinée', '🇬🇳'),
('Guéckédou', 'Guinée', '🇬🇳'),

-- Sierra Leone
('Freetown', 'Sierra Leone', '🇸🇱'),
('Bo', 'Sierra Leone', '🇸🇱'),
('Kenema', 'Sierra Leone', '🇸🇱'),
('Makeni', 'Sierra Leone', '🇸🇱'),
('Koidu', 'Sierra Leone', '🇸🇱'),
('Port Loko', 'Sierra Leone', '🇸🇱'),
('Waterloo', 'Sierra Leone', '🇸🇱'),
('Lunsar', 'Sierra Leone', '🇸🇱'),
('Kabala', 'Sierra Leone', '🇸🇱'),
('Kailahun', 'Sierra Leone', '🇸🇱'),

-- Liberia
('Monrovia', 'Liberia', '🇱🇷'),
('Gbarnga', 'Liberia', '🇱🇷'),
('Kakata', 'Liberia', '🇱🇷'),
('Bensonville', 'Liberia', '🇱🇷'),
('Harper', 'Liberia', '🇱🇷'),
('Voinjama', 'Liberia', '🇱🇷'),
('Buchanan', 'Liberia', '🇱🇷'),
('Zwedru', 'Liberia', '🇱🇷'),
('New Yekepa', 'Liberia', '🇱🇷'),
('Ganta', 'Liberia', '🇱🇷'),

-- Mauritanie
('Nouakchott', 'Mauritanie', '🇲🇷'),
('Nouadhibou', 'Mauritanie', '🇲🇷'),
('Kiffa', 'Mauritanie', '🇲🇷'),
('Rosso', 'Mauritanie', '🇲🇷'),
('Kaédi', 'Mauritanie', '🇲🇷'),
('Zouerate', 'Mauritanie', '🇲🇷'),
('Atar', 'Mauritanie', '🇲🇷'),
('Akjoujt', 'Mauritanie', '🇲🇷'),
('Sélibaby', 'Mauritanie', '🇲🇷'),
('Néma', 'Mauritanie', '🇲🇷'),

-- Gambie
('Banjul', 'Gambie', '🇬🇲'),
('Serekunda', 'Gambie', '🇬🇲'),
('Brikama', 'Gambie', '🇬🇲'),
('Bakau', 'Gambie', '🇬🇲'),
('Farafenni', 'Gambie', '🇬🇲'),
('Lamin', 'Gambie', '🇬🇲'),
('Sukuta', 'Gambie', '🇬🇲'),
('Basse Santa Su', 'Gambie', '🇬🇲'),
('Gunjur', 'Gambie', '🇬🇲'),
('Soma', 'Gambie', '🇬🇲'),

-- Guinée-Bissau
('Bissau', 'Guinée-Bissau', '🇬🇼'),
('Bafatá', 'Guinée-Bissau', '🇬🇼'),
('Gabú', 'Guinée-Bissau', '🇬🇼'),
('Bissorã', 'Guinée-Bissau', '🇬🇼'),
('Bolama', 'Guinée-Bissau', '🇬🇼'),
('Cacheu', 'Guinée-Bissau', '🇬🇼'),
('Bubaque', 'Guinée-Bissau', '🇬🇼'),
('Catió', 'Guinée-Bissau', '🇬🇼'),
('Mansôa', 'Guinée-Bissau', '🇬🇼'),
('Buba', 'Guinée-Bissau', '🇬🇼'),

-- Cap-Vert
('Praia', 'Cap-Vert', '🇨🇻'),
('Mindelo', 'Cap-Vert', '🇨🇻'),
('Santa Maria', 'Cap-Vert', '🇨🇻'),
('Assomada', 'Cap-Vert', '🇨🇻'),
('Porto Novo', 'Cap-Vert', '🇨🇻'),
('Espargos', 'Cap-Vert', '🇨🇻'),
('São Filipe', 'Cap-Vert', '🇨🇻'),
('Pedra Badejo', 'Cap-Vert', '🇨🇻'),
('Tarrafal', 'Cap-Vert', '🇨🇻'),
('Vila do Maio', 'Cap-Vert', '🇨🇻'),

-- Sao Tomé-et-Principe
('São Tomé', 'Sao Tomé-et-Principe', '🇸🇹'),
('Santo António', 'Sao Tomé-et-Principe', '🇸🇹'),
('Trindade', 'Sao Tomé-et-Principe', '🇸🇹'),
('Neves', 'Sao Tomé-et-Principe', '🇸🇹'),
('Santa Cruz', 'Sao Tomé-et-Principe', '🇸🇹'),
('Santana', 'Sao Tomé-et-Principe', '🇸🇹'),
('Guadalupe', 'Sao Tomé-et-Principe', '🇸🇹'),
('São João dos Angolares', 'Sao Tomé-et-Principe', '🇸🇹'),
('Porto Alegre', 'Sao Tomé-et-Principe', '🇸🇹'),
('Ribeira Afonso', 'Sao Tomé-et-Principe', '🇸🇹'),

-- Botswana
('Gaborone', 'Botswana', '🇧🇼'),
('Francistown', 'Botswana', '🇧🇼'),
('Maun', 'Botswana', '🇧🇼'),
('Molepolole', 'Botswana', '🇧🇼'),
('Serowe', 'Botswana', '🇧🇼'),
('Selibe Phikwe', 'Botswana', '🇧🇼'),
('Kanye', 'Botswana', '🇧🇼'),
('Mochudi', 'Botswana', '🇧🇼'),
('Mahalapye', 'Botswana', '🇧🇼'),
('Palapye', 'Botswana', '🇧🇼'),

-- Namibie
('Windhoek', 'Namibie', '🇳🇦'),
('Walvis Bay', 'Namibie', '🇳🇦'),
('Swakopmund', 'Namibie', '🇳🇦'),
('Rundu', 'Namibie', '🇳🇦'),
('Oshakati', 'Namibie', '🇳🇦'),
('Rehoboth', 'Namibie', '🇳🇦'),
('Katima Mulilo', 'Namibie', '🇳🇦'),
('Otjiwarongo', 'Namibie', '🇳🇦'),
('Okahandja', 'Namibie', '🇳🇦'),
('Ondangwa', 'Namibie', '🇳🇦'),

-- Eswatini
('Mbabane', 'Eswatini', '🇸🇿'),
('Manzini', 'Eswatini', '🇸🇿'),
('Big Bend', 'Eswatini', '🇸🇿'),
('Malkerns', 'Eswatini', '🇸🇿'),
('Nhlangano', 'Eswatini', '🇸🇿'),
('Siteki', 'Eswatini', '🇸🇿'),
('Piggs Peak', 'Eswatini', '🇸🇿'),
('Lobamba', 'Eswatini', '🇸🇿'),
('Hluti', 'Eswatini', '🇸🇿'),
('Kwaluseni', 'Eswatini', '🇸🇿'),

-- Lesotho
('Maseru', 'Lesotho', '🇱🇸'),
('Teyateyaneng', 'Lesotho', '🇱🇸'),
('Mafeteng', 'Lesotho', '🇱🇸'),
('Hlotse', 'Lesotho', '🇱🇸'),
('Mohale''s Hoek', 'Lesotho', '🇱🇸'),
('Maputsoe', 'Lesotho', '🇱🇸'),
('Qacha''s Nek', 'Lesotho', '🇱🇸'),
('Quthing', 'Lesotho', '🇱🇸'),
('Mokhotlong', 'Lesotho', '🇱🇸'),
('Thaba-Tseka', 'Lesotho', '🇱🇸'),

-- Malawi
('Lilongwe', 'Malawi', '🇲🇼'),
('Blantyre', 'Malawi', '🇲🇼'),
('Mzuzu', 'Malawi', '🇲🇼'),
('Zomba', 'Malawi', '🇲🇼'),
('Mangochi', 'Malawi', '🇲🇼'),
('Kasungu', 'Malawi', '🇲🇼'),
('Karonga', 'Malawi', '🇲🇼'),
('Salima', 'Malawi', '🇲🇼'),
('Liwonde', 'Malawi', '🇲🇼'),
('Nkhotakota', 'Malawi', '🇲🇼'),

-- Seychelles
('Victoria', 'Seychelles', '🇸🇨'),
('Anse Boileau', 'Seychelles', '🇸🇨'),
('Bel Ombre', 'Seychelles', '🇸🇨'),
('Beau Vallon', 'Seychelles', '🇸🇨'),
('Cascade', 'Seychelles', '🇸🇨'),
('Anse Royale', 'Seychelles', '🇸🇨'),
('Takamaka', 'Seychelles', '🇸🇨'),
('Port Glaud', 'Seychelles', '🇸🇨'),
('La Digue', 'Seychelles', '🇸🇨'),
('Praslin', 'Seychelles', '🇸🇨'),

-- Comores
('Moroni', 'Comores', '🇰🇲'),
('Mutsamudu', 'Comores', '🇰🇲'),
('Fomboni', 'Comores', '🇰🇲'),
('Domoni', 'Comores', '🇰🇲'),
('Tsimbeo', 'Comores', '🇰🇲'),
('Ouani', 'Comores', '🇰🇲'),
('Sima', 'Comores', '🇰🇲'),
('Mirontsi', 'Comores', '🇰🇲'),
('Mbeni', 'Comores', '🇰🇲'),
('Adda-Douéni', 'Comores', '🇰🇲')
ON CONFLICT (id) DO NOTHING;